{{- range $k, $v := .Values.verification.nodes }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # This is the full name of your deployment. It must be unique
  name: {{ $k }}
  labels:
    app: {{ $k }}
    nodeType: verification
    service: flow
    networkId: {{ $.Values.networkId }}

spec:
  serviceName: {{ $k }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ $k }}
      nodeType: verification
      service: flow
      networkId: {{ $.Values.networkId }}

  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
      labels:
        app: {{ $k }}
        networkId: {{ $.Values.networkId }}
        nodeType: verification
        owner: {{ $.Values.owner }}
        service: flow
    spec:
      containers:
        - name: {{ $k }}
          image: {{ $v.image }}
          {{ if $v.imagePullPolicy }}
          imagePullPolicy: {{ $v.imagePullPolicy| toYaml | nindent 12 }}
          {{ else}}
          imagePullPolicy: {{ $.Values.verification.defaults.imagePullPolicy | toYaml | nindent 12 }}
          {{ end }}

          args: {{ $v.args | toYaml | nindent 12}}

          {{ if $v.ports }}
          ports: {{ $v.ports | toYaml | nindent 12 }}
          {{ else}}
          ports: {{ $.Values.verification.defaults.containerPorts | toYaml | nindent 12 }}
          {{ end }}
  
          {{ if $v.env }}
          env: {{ $v.env | toYaml | nindent 12 }}
          {{ else}}
          env: {{ $.Values.verification.defaults.env | toYaml | nindent 12 }}
          {{ end }}
          
          volumeMounts:
            - name: data
              mountPath: /data

            - name: node-info-priv-json
              readOnly: true
              mountPath: /bootstrap/private-root-information/private-node-info_{{ $v.nodeId }}/node-info.priv.json
              subPath: node-info.priv.json

            - name: node-info-pub-json
              readOnly: true
              mountPath: /bootstrap/public-root-information/node-infos.pub.json
              subPath: node-infos.pub.json

            - name: root-block-json
              readOnly: true
              mountPath: /bootstrap/public-root-information/root-block.json
              subPath: root-block.json

            - name: root-protocol-state-snapshot-json
              readOnly: true
              mountPath: /bootstrap/public-root-information/root-protocol-state-snapshot.json
              subPath: root-protocol-state-snapshot.json

            - name: secretsdb-key
              readOnly: true
              mountPath: /bootstrap/private-root-information/private-node-info_{{ $v.nodeId }}/secretsdb-key
              subPath: secretsdb-key

          {{ if $v.resources }}
          resources: {{ $v.resources | toYaml | nindent 12 }}
          {{ else}}
          resources: {{ $.Values.verification.defaults.resources | toYaml | nindent 12 }}
          {{ end }}

      volumes:

        - name: node-info-priv-json
          secret: 
            secretName: {{ $.Values.networkId }}.{{ $v.nodeId }}.node-info.priv.json

        - name: node-info-pub-json
          secret: 
            secretName: {{ $.Values.networkId }}.node-infos.pub.json

        - name: root-block-json
          secret: 
            secretName: {{ $.Values.networkId }}.root-block.json

        - name: root-protocol-state-snapshot-json
          secret: 
            secretName: {{ $.Values.networkId }}.root-protocol-state-snapshot.json

        - name: secretsdb-key
          secret: 
            secretName: {{ $.Values.networkId }}.{{ $v.nodeId }}.secretsdb-key

  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          networkId: {{ $.Values.networkId }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            {{ if $v.storage }}
            storage: {{ $v.storage }}
            {{ else}}
            storage: {{ $.Values.verification.defaults.storage }}
            {{ end }}
{{- end }}

{{- range $k, $v := $.Values.verification.nodes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $k }}
  labels:
    app: {{ $k }}
    networkId: {{ $.Values.networkId }}
    owner: {{ $.Values.owner }}
spec:
  {{ if $v.servicePorts }}
  ports: {{ $v.servicePorts | toYaml | nindent 12 }}
  {{ else}}
  ports: {{ $.Values.verification.defaults.servicePorts  | toYaml | nindent 4 }}
  {{ end }}
  selector:
    app: {{ $k }}
  type: NodePort
{{- end }}