// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	fvm "github.com/onflow/flow-go/fvm"
	mock "github.com/stretchr/testify/mock"

	state "github.com/onflow/flow-go/fvm/state"
)

// Procedure is an autogenerated mock type for the Procedure type
type Procedure struct {
	mock.Mock
}

// Run provides a mock function with given fields: vm, ctx, st, programs
func (_m *Procedure) Run(vm *fvm.VirtualMachine, ctx fvm.Context, st *state.State, programs *fvm.Programs) error {
	ret := _m.Called(vm, ctx, st, programs)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fvm.VirtualMachine, fvm.Context, *state.State, *fvm.Programs) error); ok {
		r0 = rf(vm, ctx, st, programs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
