# The version of golangci-lint used to build the custom binary
version: v1.63.4

# The name of the custom binary
name: custom-gcl

# The directory path used to store the custom binary.
destination: ./tools/

# The list of the plugins to integrate inside the custom binary.
plugins:
  # a plugin from a Go proxy
  - module: 'github.com/golangci/example-linter'
    version: latest
