# The version of golangci-lint used to build the custom binary
version: v2.8.1

# The name of the custom binary
name: custom-gcl

# The directory path used to store the custom binary.
destination: ./tools/

plugins:
  - module: 'github.com/onflow/flow-go'
    path: ./tools/structwrite
