run:
  timeout: 10m

linters-settings:
  goimports:
    # enforced by linter
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/onflow/flow-go/

  # used to generate canonical import ordering
  # not enforced by linter
  gci:
    sections:
      - standard                           # 1. standard library
      - default                            # 2. external packages
      - prefix(github.com/onflow/)         # 3. org packages
      - prefix(github.com/onflow/flow-go/) # 4. project packages
    skip-generated: true
    custom-order: true

  gosec:
    # To select a subset of rules to run.
    # Available rules: https://github.com/securego/gosec#available-rules
    includes:
      - G401
      - G402
      - G501
      - G502
      - G503
      - G505

  staticcheck:
    # Disable SA1019 to allow use of deprecated label
    checks: ["all", "-SA1019"]

  custom:
    structwrite:
      type: module
      description: "disallow struct field writes outside constructor"
      original-url: "github.com/onflow/flow-go/tools/structwrite"

linters:
  enable:
    - goimports
    - gosec
    - structwrite

issues:
  exclude-rules:
    - path: _test\.go # disable some linters on test files
      linters:
        - unused
        - structwrite
    - path: 'consensus/hotstuff/helper/*' # disable some linters on test helper files
      linters:
        - structwrite
    - path: 'utils/unittest/*' # disable some linters on test files
      linters:
        - structwrite
    - path: 'consensus/hotstuff/helper/*' # disable some linters on test files
      linters:
        - structwrite
    - path: 'engine/execution/testutil/*' # disable some linters on test files
      linters:
        - structwrite
    # typecheck currently not handling the way we do function inheritance well
    # disabling for now
    - path: 'cmd/access/node_build/*'
      linters:
        - typecheck
    - path: 'cmd/observer/node_builder/*'
      linters:
        - typecheck
    - path: 'follower/*'
      linters:
        - typecheck
