#!/bin/bash 
cmake -DWITH="ALL" -DCHECK=off -DARITH=gmp -DFP_PRIME=254 -DFP_QNRES=on -DFP_METHD="BASIC;COMBA;COMBA;MONTY;LOWER;SLIDE" DFP_QNRES=on -DPC_METHD="PRIME" -DPP_METHD="INTEG;INTEG;LAZYR;OATEP" -DCOMP="-O2 -funroll-loops -fomit-frame-pointer" $1
