// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"
	mock "github.com/stretchr/testify/mock"
)

// NewConnectorHost creates a new instance of ConnectorHost. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectorHost(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectorHost {
	mock := &ConnectorHost{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConnectorHost is an autogenerated mock type for the ConnectorHost type
type ConnectorHost struct {
	mock.Mock
}

type ConnectorHost_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectorHost) EXPECT() *ConnectorHost_Expecter {
	return &ConnectorHost_Expecter{mock: &_m.Mock}
}

// ClosePeer provides a mock function for the type ConnectorHost
func (_mock *ConnectorHost) ClosePeer(peerId peer.ID) error {
	ret := _mock.Called(peerId)

	if len(ret) == 0 {
		panic("no return value specified for ClosePeer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(peer.ID) error); ok {
		r0 = returnFunc(peerId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ConnectorHost_ClosePeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClosePeer'
type ConnectorHost_ClosePeer_Call struct {
	*mock.Call
}

// ClosePeer is a helper method to define mock.On call
//   - peerId peer.ID
func (_e *ConnectorHost_Expecter) ClosePeer(peerId interface{}) *ConnectorHost_ClosePeer_Call {
	return &ConnectorHost_ClosePeer_Call{Call: _e.mock.On("ClosePeer", peerId)}
}

func (_c *ConnectorHost_ClosePeer_Call) Run(run func(peerId peer.ID)) *ConnectorHost_ClosePeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 peer.ID
		if args[0] != nil {
			arg0 = args[0].(peer.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConnectorHost_ClosePeer_Call) Return(err error) *ConnectorHost_ClosePeer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ConnectorHost_ClosePeer_Call) RunAndReturn(run func(peerId peer.ID) error) *ConnectorHost_ClosePeer_Call {
	_c.Call.Return(run)
	return _c
}

// Connections provides a mock function for the type ConnectorHost
func (_mock *ConnectorHost) Connections() []network.Conn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connections")
	}

	var r0 []network.Conn
	if returnFunc, ok := ret.Get(0).(func() []network.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]network.Conn)
		}
	}
	return r0
}

// ConnectorHost_Connections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connections'
type ConnectorHost_Connections_Call struct {
	*mock.Call
}

// Connections is a helper method to define mock.On call
func (_e *ConnectorHost_Expecter) Connections() *ConnectorHost_Connections_Call {
	return &ConnectorHost_Connections_Call{Call: _e.mock.On("Connections")}
}

func (_c *ConnectorHost_Connections_Call) Run(run func()) *ConnectorHost_Connections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectorHost_Connections_Call) Return(conns []network.Conn) *ConnectorHost_Connections_Call {
	_c.Call.Return(conns)
	return _c
}

func (_c *ConnectorHost_Connections_Call) RunAndReturn(run func() []network.Conn) *ConnectorHost_Connections_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type ConnectorHost
func (_mock *ConnectorHost) ID() peer.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 peer.ID
	if returnFunc, ok := ret.Get(0).(func() peer.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(peer.ID)
	}
	return r0
}

// ConnectorHost_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type ConnectorHost_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *ConnectorHost_Expecter) ID() *ConnectorHost_ID_Call {
	return &ConnectorHost_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *ConnectorHost_ID_Call) Run(run func()) *ConnectorHost_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectorHost_ID_Call) Return(iD peer.ID) *ConnectorHost_ID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *ConnectorHost_ID_Call) RunAndReturn(run func() peer.ID) *ConnectorHost_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnectedTo provides a mock function for the type ConnectorHost
func (_mock *ConnectorHost) IsConnectedTo(peerId peer.ID) bool {
	ret := _mock.Called(peerId)

	if len(ret) == 0 {
		panic("no return value specified for IsConnectedTo")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(peer.ID) bool); ok {
		r0 = returnFunc(peerId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConnectorHost_IsConnectedTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnectedTo'
type ConnectorHost_IsConnectedTo_Call struct {
	*mock.Call
}

// IsConnectedTo is a helper method to define mock.On call
//   - peerId peer.ID
func (_e *ConnectorHost_Expecter) IsConnectedTo(peerId interface{}) *ConnectorHost_IsConnectedTo_Call {
	return &ConnectorHost_IsConnectedTo_Call{Call: _e.mock.On("IsConnectedTo", peerId)}
}

func (_c *ConnectorHost_IsConnectedTo_Call) Run(run func(peerId peer.ID)) *ConnectorHost_IsConnectedTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 peer.ID
		if args[0] != nil {
			arg0 = args[0].(peer.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConnectorHost_IsConnectedTo_Call) Return(b bool) *ConnectorHost_IsConnectedTo_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConnectorHost_IsConnectedTo_Call) RunAndReturn(run func(peerId peer.ID) bool) *ConnectorHost_IsConnectedTo_Call {
	_c.Call.Return(run)
	return _c
}

// IsProtected provides a mock function for the type ConnectorHost
func (_mock *ConnectorHost) IsProtected(peerId peer.ID) bool {
	ret := _mock.Called(peerId)

	if len(ret) == 0 {
		panic("no return value specified for IsProtected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(peer.ID) bool); ok {
		r0 = returnFunc(peerId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ConnectorHost_IsProtected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProtected'
type ConnectorHost_IsProtected_Call struct {
	*mock.Call
}

// IsProtected is a helper method to define mock.On call
//   - peerId peer.ID
func (_e *ConnectorHost_Expecter) IsProtected(peerId interface{}) *ConnectorHost_IsProtected_Call {
	return &ConnectorHost_IsProtected_Call{Call: _e.mock.On("IsProtected", peerId)}
}

func (_c *ConnectorHost_IsProtected_Call) Run(run func(peerId peer.ID)) *ConnectorHost_IsProtected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 peer.ID
		if args[0] != nil {
			arg0 = args[0].(peer.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConnectorHost_IsProtected_Call) Return(b bool) *ConnectorHost_IsProtected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ConnectorHost_IsProtected_Call) RunAndReturn(run func(peerId peer.ID) bool) *ConnectorHost_IsProtected_Call {
	_c.Call.Return(run)
	return _c
}

// PeerInfo provides a mock function for the type ConnectorHost
func (_mock *ConnectorHost) PeerInfo(peerId peer.ID) peer.AddrInfo {
	ret := _mock.Called(peerId)

	if len(ret) == 0 {
		panic("no return value specified for PeerInfo")
	}

	var r0 peer.AddrInfo
	if returnFunc, ok := ret.Get(0).(func(peer.ID) peer.AddrInfo); ok {
		r0 = returnFunc(peerId)
	} else {
		r0 = ret.Get(0).(peer.AddrInfo)
	}
	return r0
}

// ConnectorHost_PeerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerInfo'
type ConnectorHost_PeerInfo_Call struct {
	*mock.Call
}

// PeerInfo is a helper method to define mock.On call
//   - peerId peer.ID
func (_e *ConnectorHost_Expecter) PeerInfo(peerId interface{}) *ConnectorHost_PeerInfo_Call {
	return &ConnectorHost_PeerInfo_Call{Call: _e.mock.On("PeerInfo", peerId)}
}

func (_c *ConnectorHost_PeerInfo_Call) Run(run func(peerId peer.ID)) *ConnectorHost_PeerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 peer.ID
		if args[0] != nil {
			arg0 = args[0].(peer.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConnectorHost_PeerInfo_Call) Return(addrInfo peer.AddrInfo) *ConnectorHost_PeerInfo_Call {
	_c.Call.Return(addrInfo)
	return _c
}

func (_c *ConnectorHost_PeerInfo_Call) RunAndReturn(run func(peerId peer.ID) peer.AddrInfo) *ConnectorHost_PeerInfo_Call {
	_c.Call.Return(run)
	return _c
}
