// Code generated by mockery v2.21.4. DO NOT EDIT.

package mockp2p

import (
	mock "github.com/stretchr/testify/mock"

	peer "github.com/libp2p/go-libp2p/core/peer"

	pubsub "github.com/libp2p/go-libp2p-pubsub"
)

// GossipSubControlMetricsObserver is an autogenerated mock type for the GossipSubControlMetricsObserver type
type GossipSubControlMetricsObserver struct {
	mock.Mock
}

// ObserveRPC provides a mock function with given fields: _a0, _a1
func (_m *GossipSubControlMetricsObserver) ObserveRPC(_a0 peer.ID, _a1 *pubsub.RPC) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewGossipSubControlMetricsObserver interface {
	mock.TestingT
	Cleanup(func())
}

// NewGossipSubControlMetricsObserver creates a new instance of GossipSubControlMetricsObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGossipSubControlMetricsObserver(t mockConstructorTestingTNewGossipSubControlMetricsObserver) *GossipSubControlMetricsObserver {
	mock := &GossipSubControlMetricsObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
