// Code generated by mockery v2.21.4. DO NOT EDIT.

package mockp2p

import (
	mock "github.com/stretchr/testify/mock"

	pubsub "github.com/libp2p/go-libp2p-pubsub"
)

// ScoreOptionBuilder is an autogenerated mock type for the ScoreOptionBuilder type
type ScoreOptionBuilder struct {
	mock.Mock
}

// BuildFlowPubSubScoreOption provides a mock function with given fields:
func (_m *ScoreOptionBuilder) BuildFlowPubSubScoreOption() pubsub.Option {
	ret := _m.Called()

	var r0 pubsub.Option
	if rf, ok := ret.Get(0).(func() pubsub.Option); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pubsub.Option)
		}
	}

	return r0
}

type mockConstructorTestingTNewScoreOptionBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewScoreOptionBuilder creates a new instance of ScoreOptionBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScoreOptionBuilder(t mockConstructorTestingTNewScoreOptionBuilder) *ScoreOptionBuilder {
	mock := &ScoreOptionBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
