// Code generated by mockery v2.13.1. DO NOT EDIT.

package mockp2p

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pubsub "github.com/libp2p/go-libp2p-pubsub"
)

// Subscription is an autogenerated mock type for the Subscription type
type Subscription struct {
	mock.Mock
}

// Cancel provides a mock function with given fields:
func (_m *Subscription) Cancel() {
	_m.Called()
}

// Next provides a mock function with given fields: _a0
func (_m *Subscription) Next(_a0 context.Context) (*pubsub.Message, error) {
	ret := _m.Called(_a0)

	var r0 *pubsub.Message
	if rf, ok := ret.Get(0).(func(context.Context) *pubsub.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSubscription interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubscription creates a new instance of Subscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubscription(t mockConstructorTestingTNewSubscription) *Subscription {
	mock := &Subscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
