// Code generated by capnpc-go. DO NOT EDIT.

package captain

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type GuaranteedCollection struct{ capnp.Struct }

// GuaranteedCollection_TypeID is the unique identifier for the type GuaranteedCollection.
const GuaranteedCollection_TypeID = 0xc45eaaad82049c1b

func NewGuaranteedCollection(s *capnp.Segment) (GuaranteedCollection, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return GuaranteedCollection{st}, err
}

func NewRootGuaranteedCollection(s *capnp.Segment) (GuaranteedCollection, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return GuaranteedCollection{st}, err
}

func ReadRootGuaranteedCollection(msg *capnp.Message) (GuaranteedCollection, error) {
	root, err := msg.RootPtr()
	return GuaranteedCollection{root.Struct()}, err
}

func (s GuaranteedCollection) String() string {
	str, _ := text.Marshal(0xc45eaaad82049c1b, s.Struct)
	return str
}

func (s GuaranteedCollection) Hash() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return []byte(p.Data()), err
}

func (s GuaranteedCollection) HasHash() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s GuaranteedCollection) SetHash(v []byte) error {
	return s.Struct.SetData(0, v)
}

func (s GuaranteedCollection) Signature() ([]byte, error) {
	p, err := s.Struct.Ptr(1)
	return []byte(p.Data()), err
}

func (s GuaranteedCollection) HasSignature() bool {
	p, err := s.Struct.Ptr(1)
	return p.IsValid() || err != nil
}

func (s GuaranteedCollection) SetSignature(v []byte) error {
	return s.Struct.SetData(1, v)
}

// GuaranteedCollection_List is a list of GuaranteedCollection.
type GuaranteedCollection_List struct{ capnp.List }

// NewGuaranteedCollection creates a new list of GuaranteedCollection.
func NewGuaranteedCollection_List(s *capnp.Segment, sz int32) (GuaranteedCollection_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return GuaranteedCollection_List{l}, err
}

func (s GuaranteedCollection_List) At(i int) GuaranteedCollection {
	return GuaranteedCollection{s.List.Struct(i)}
}

func (s GuaranteedCollection_List) Set(i int, v GuaranteedCollection) error {
	return s.List.SetStruct(i, v.Struct)
}

func (s GuaranteedCollection_List) String() string {
	str, _ := text.MarshalList(0xc45eaaad82049c1b, s.List)
	return str
}

// GuaranteedCollection_Promise is a wrapper for a GuaranteedCollection promised by a client call.
type GuaranteedCollection_Promise struct{ *capnp.Pipeline }

func (p GuaranteedCollection_Promise) Struct() (GuaranteedCollection, error) {
	s, err := p.Pipeline.Struct()
	return GuaranteedCollection{s}, err
}

const schema_ca5023959d73b9b5 = "x\xda2\x90ct`2d\x9d\xce\xce\xc0\x10\x18\xc1" +
	"\xca\xf6_z\x0eK\xd3\xdaUqG\x18\x04\x15\x18\xff" +
	"o\xddY<w\xaar\xc0)\x06V&v\x06\x06\xe3" +
	"\x8d\xcc\xab\x18\x85O2\xb330\x08\x1fe.gx" +
	"\xf1\xbf89#57Q?\x995\xb1\xa0$13" +
	"O?9?''5\xb9$3?O/9\xb1 " +
	"\xaf\xc0\xca\xbd4\xb1(1\xaf$55\xc5\x19,\xc5" +
	"\x0f\x92\x0b`d\x0c\xe4`fa``ad`\x10" +
	"\xd4\xd4b`\x08Taf\x0c4`b\x14dd\x14" +
	"a\x04\x09\xea\x0610\x04\xea03\x06Z01\xf2" +
	"g$\x16g0\xf2201\xf220\xfe/\xceL" +
	"\xcfK,)-b`L\x85\x89\x01\x02\x00\x00\xff\xff" +
	"kW1%"

func init() {
	schemas.Register(schema_ca5023959d73b9b5,
		0xc45eaaad82049c1b)
}
