// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package collect

import (
	"github.com/dapperlabs/bamboo-node/internal/roles/collect/config"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configConfig := config.New()
	logger := logrus.New()
	controller := NewController(logger)
	server, err := NewServer(configConfig, logger, controller)
	if err != nil {
		return nil, err
	}
	return server, nil
}
