{
 "title": "Loader",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Loader total transactions",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flow_execution_effort_estimation_transactions_sent[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(flow_execution_effort_estimation_transactions_received[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "flow_execution_effort_estimation_transactions_in_flight",
     "legendFormat": "in flight"
    }
   ]
  },
  {
   "title": "Loader TPS",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(flow_execution_effort_estimation_loader_transaction_sent[$__rate_interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(flow_execution_effort_estimation_loader_transaction_received[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "flow_execution_effort_estimation_loader_desired_tps",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Accounts",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(flow_execution_effort_estimation_accounts_created[$__rate_interval])",
     "legendFormat": "accounts created"
    },
    {
     "expr": "flow_execution_effort_estimation_account_demand",
     "legendFormat": "accounts demanded"
    }
   ]
  },
  {
   "title": "Transaction flight time",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "flow_execution_effort_estimation_transaction_flight_time_seconds",
     "legendFormat": "quantile {{quantile}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "flow_execution_effort_estimation_average_flight_duration"
    }
   ]
  },
  {
   "title": "TPS controller parameters",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "flow_execution_effort_estimation_loader_controller_parameters",
     "legendFormat": "{{parameter}}"
    }
   ]
  }
 ]
}