{
 "title": "localnet - General",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(up, network)" } }
  ]
 },
 "panels": [
  {
   "title": "Loader Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loader Tx Submission",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "loader_transactions_per_second_configured",
       "legendFormat": "load_configured"
      },
      {
       "expr": "rate(loader_transactions_sent[1m])",
       "legendFormat": "tps_in"
      },
      {
       "expr": "rate(loader_transactions_executed[1m])",
       "legendFormat": "tps_out"
      }
     ]
    },
    {
     "title": "Transaction execution time",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(loader_transactions_tte_seconds_bucket{}[$__rate_interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to Finalization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "access_transaction_timing_time_to_finalized_seconds{network=\"$network\",num=\"001\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Time to Execution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "access_transaction_timing_time_to_executed_seconds{network=\"$network\",num=\"001\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Time to Finalized and Executed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "access_transaction_timing_time_to_finalized_executed_seconds{network=\"$network\",num=\"001\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Access Network Messages (deduplicated)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(network_gossip_duplicate_messages_dropped{network=\"$network\",role=\"access\"}[2m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Access Network Messages (in)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(network_gossip_inbound_message_size_bytes_count{network=\"$network\",role=\"access\"}[2m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Access Network Messages (out)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(network_gossip_outbound_message_size_bytes_count{network=\"$network\",role=\"access\"}[2m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Collection Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection Errors",
     "type": "logs",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{role=\"collection\"} |= \"error\" | json | __error__ != \"JSONParserErr\" | level=\"error\"",
       "maxLines": 100
      }
     ]
    },
    {
     "title": "Collection Finalization Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "Blocks / s" }
     ],
     "targets": [
      {
       "expr": "avg by (chain) (rate(collection_proposal_finalized_height{role=\"collection\",network=\"$network\"}[2m]))",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "Transaction Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short", "label": "tx / s" }
     ],
     "targets": [
      {
       "expr": "avg by (chain) (rate(collection_proposal_guarantees_size_transactions_sum{role=\"collection\",network=\"$network\"}[2m]))",
       "legendFormat": "collection-{{chain}}"
      }
     ]
    },
    {
     "title": "Collection Timeout",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consensus_hotstuff_timeout_seconds{network=\"$network\",role=\"collection\"}",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    },
    {
     "title": "Collection Network Messages (deduplicated)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(network_gossip_duplicate_messages_dropped{network=\"$network\",role=\"collection\"}[2m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Collection Network Messages (in)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(network_gossip_inbound_message_size_bytes_count{network=\"$network\",role=\"collection\"}[2m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Collection Network Messages (out)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic) (rate(network_gossip_outbound_message_size_bytes_count{network=\"$network\",role=\"collection\"}[2m]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\",network=\"$network\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Go routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{network=\"$network\", role=\"collection\"}",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Active_bytes{network=\"$network\",role=\"collection\"}",
       "legendFormat": "{{role}}"
      }
     ]
    }
   ]
  },
  { "title": "Consensus Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Consensus Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{role=\"consensus\"} |= \"error\" | json | __error__ != \"JSONParserErr\" | level=\"error\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Consensus Block Rate (Blocks Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (role) (sum by (num) (rate(consensus_compliance_finalized_blocks_total{role=\"consensus\",network=\"$network\"}[2m])))",
     "legendFormat": "Finalization Rate"
    },
    {
     "expr": "avg by (role) (rate(consensus_compliance_sealed_blocks_total{role=\"consensus\",network=\"$network\"}[2m]))",
     "legendFormat": "Seal Rate"
    }
   ]
  },
  {
   "title": "Consensus Views",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(consensus_hotstuff_cur_view{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Max View"
    },
    {
     "expr": "min(consensus_hotstuff_cur_view{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Min View"
    }
   ]
  },
  {
   "title": "Consensus Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "consensus_hotstuff_timeout_seconds{role=\"consensus\",network=\"$network\"}"
    }
   ]
  },
  {
   "title": "Consensus Views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(consensus_hotstuff_cur_view{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Views"
    }
   ]
  },
  {
   "title": "Finalization Rate (Blocks Per Second)",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (role) (sum by (num) (rate(consensus_compliance_finalized_blocks_total{role=\"consensus\",network=\"$network\"}[2m])))",
     "legendFormat": "Max"
    },
    {
     "expr": "min by (role) (sum by (num) (rate(consensus_compliance_finalized_blocks_total{role=\"consensus\",network=\"$network\"}[2m])))",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Consensus Block Height",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(consensus_compliance_finalized_height{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Max Finalized"
    },
    {
     "expr": "min(consensus_compliance_finalized_height{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Min Finalized"
    },
    {
     "expr": "max(consensus_compliance_sealed_height{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Max Sealed"
    },
    {
     "expr": "min(consensus_compliance_sealed_height{role=\"consensus\",network=\"$network\"})",
     "legendFormat": "Min Sealed"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\",network=\"$network\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalizing Consensus Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(sum by (num) (rate(consensus_compliance_finalized_blocks_total{role=\"consensus\",network=\"$network\"}[2m]))) > 0)"
    }
   ]
  },
  {
   "title": "Unsealed finalized blocks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(consensus_compliance_finalized_height{role=\"consensus\",network=\"$network\"}) - max(consensus_compliance_sealed_height{role=\"consensus\",network=\"$network\"})"
    }
   ]
  },
  {
   "title": "Epoch Phase",
   "type": "stat",
   "description": "The phase value for the current epoch. The phase can be one of 1-Staking, 2-Setup, 3-Committed. Each epoch transitions through phases like 1->2->3.",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consensus_compliance_current_epoch_phase{network=\"$network\"})",
     "legendFormat": "Phase"
    }
   ]
  },
  {
   "title": "Epoch Counter",
   "type": "stat",
   "description": "The counter value for the current epoch. The counter is incremented after each epoch transition, including during sporks.",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(consensus_compliance_current_epoch_counter{network=\"$network\"})"
    }
   ]
  },
  {
   "title": "Epoch Timing",
   "type": "stat",
   "description": "Tracks the approximate number of hours remaining until the next epoch switchover. (Denominator in query is average views/hour)",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(consensus_compliance_current_dkg_phase3_final_view{network=\"$network\"})-max(consensus_hotstuff_cur_view{role=\"consensus\",network=\"$network\"}))",
     "legendFormat": "Views to DKG End"
    },
    {
     "expr": "(max(consensus_compliance_current_epoch_final_view{network=\"$network\"})-max(consensus_hotstuff_cur_view{role=\"consensus\",network=\"$network\"}))",
     "legendFormat": "Views To Epoch End"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{network=\"$network\", role=\"consensus\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Consensus Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_Active_bytes{role!=\"ansible\",network=\"$network\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Execution Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Transaction Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "tx / s" }
   ],
   "targets": [
    {
     "expr": "rate(execution_runtime_total_executed_transactions{role=\"execution\",network=\"$network\"}[2m])",
     "legendFormat": "execution-{{num}}"
    }
   ]
  },
  {
   "title": "Execution Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "seconds / block" }
   ],
   "targets": [
    {
     "expr": "rate(execution_runtime_last_executed_block_height{network=\"$network\"}[2m])",
     "legendFormat": "execution-{{num}}"
    }
   ]
  },
  {
   "title": "Execution Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "{role=\"execution\"} |= \"error\" | json | __error__ != \"JSONParserErr\" | level=\"error\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Traceable TXes (>10 ms)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "{role=\"execution\"} | json | __error__ != \"JSONParserErr\" | timeSpentInMS > 10 | traceID != \"\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Transactions taking more than 10 ms",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "{role=\"execution\"} |= \"transaction executed\"  | json | timeSpentInMS > 10 | line_format \"0x{{.tx_id}} - {{.timeSpentInMS}} ms\" \n",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Last Executed Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "execution_runtime_last_executed_block_height{network=\"$network\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Execution Node Finalized Height",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "consensus_compliance_finalized_height{role=\"execution\",network=\"$network\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Verification Processed Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(verification_assigner_finalized_height{role=\"verification\",network=\"$network\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(verification_assigner_finalized_height{role=\"verification\",network=\"$network\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(verification_assigner_finalized_height{role=\"verification\",network=\"$network\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{network=\"$network\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (role) (node_memory_Active_bytes{role!=\"ansible\",network=\"$network\",role!=\"execution\"})",
     "legendFormat": "{{role}}"
    },
    {
     "expr": "(node_memory_Active_bytes{role!=\"ansible\",network=\"$network\",role=\"execution\"})",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (num, role) (rate(node_cpu_seconds_total{mode!=\"idle\",network=\"$network\"}[5m]))",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  { "title": "Verification Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Verification Result Approval Rate",
   "type": "timeseries",
   "description": "The average result approval rate of verification nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (chain) (rate(verification_verifier_result_approvals_total{role=\"verification\",network=\"$network\"}[2m]))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Verification Assigned Chunks Rate",
   "type": "timeseries",
   "description": "The average rate of incoming assigned chunks for verification nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (chain) (rate(verification_assigner_chunk_assigned_total{role=\"verification\",network=\"$network\"}[2m]))",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Chunk Data Pack Request/Reply Rate",
   "type": "timeseries",
   "description": "The average rate of requester engine on dispatching chunk data pack requests to execution nodes and receiving the chunk data response from the execution nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (chain) (rate(verification_requester_chunk_data_pack_request_message_sent_total{role=\"verification\",network=\"$network\"}[2m]))",
     "legendFormat": "requested-chunk-data-pack"
    },
    {
     "expr": "avg by (chain) (rate(verification_requester_chunk_data_response_message_received_total{role=\"verification\",network=\"$network\"}[2m]))",
     "legendFormat": "received-chunk-data-pack"
    }
   ]
  },
  {
   "title": "Verification Nodes Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_info{network=\"$network\", role=\"verification\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Verification Mempool Size",
   "type": "timeseries",
   "description": "Average mempool sizes of verification nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (chain) (storage_mempool_entries_total{resource=\"chunk_status\", role=\"verification\", network=\"$network\"})",
     "legendFormat": "Chunk Statuses"
    },
    {
     "expr": "avg by (chain) (storage_mempool_entries_total{resource=\"chunk_request\", role=\"verification\", network=\"$network\"})",
     "legendFormat": "Chunk Requests"
    }
   ]
  },
  {
   "title": "Verification Processed Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 115 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(verification_assigner_finalized_height{role=\"verification\",network=\"$network\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(verification_assigner_finalized_height{role=\"verification\",network=\"$network\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(verification_assigner_finalized_height{role=\"verification\",network=\"$network\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Networking Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average DNS Lookup Duration",
     "type": "timeseries",
     "description": "Average lookup duration over the nodes",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "(avg by (role) (rate(network_gossip_dns_lookup_duration_ms_sum{network=\"$network\"}[5m])))\n/\n(avg by (role) (rate(network_gossip_dns_lookup_duration_ms_count{network=\"$network\"}[5m])))"
      }
     ]
    },
    {
     "title": "Average Inbound Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 147 },
     "targets": [
      {
       "expr": "avg by (role)(network_queue_inbound_connection_count{network=\"$network\"})"
      }
     ]
    },
    {
     "title": "Average Outbound Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 147 },
     "targets": [
      {
       "expr": "avg by (role)(network_queue_outbound_connection_count{network=\"$network\"})"
      }
     ]
    },
    {
     "title": "TCP Bytes In (netstat)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg by (role) (irate(node_netstat_IpExt_InOctets{network=\"$network\", role!~\"tracing|loader\"}[1m]))",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    },
    {
     "title": "Network Received Bytes ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 156 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg by (role) (irate(node_network_receive_bytes_total{network=\"$network\", role!~\"tracing|loader\"}[1m]))",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    },
    {
     "title": "DNS Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 156 },
     "targets": [
      {
       "expr": "avg by (chain)(rate(network_gossip_dns_cache_miss_total{network=\"$network\"}[5m]))",
       "legendFormat": "Miss"
      },
      {
       "expr": "avg by (chain)(rate(network_gossip_dns_cache_hit_total{network=\"$network\"}[5m]))",
       "legendFormat": "Hit"
      },
      {
       "expr": "avg by (chain)(rate(network_gossip_dns_cache_invalidation_total{network=\"$network\"}[5m]))",
       "legendFormat": "Invalidation"
      }
     ]
    },
    {
     "title": "TCP Bytes Out (netstat)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg by (role) (irate(node_netstat_IpExt_OutOctets{network=\"$network\", role!~\"tracing|loader\"}[1m]))",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    },
    {
     "title": "Network Transmitted Bytes ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "avg by (role) (irate(node_network_transmit_bytes_total{network=\"$network\", role!~\"tracing|loader\"}[5m]))",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    },
    {
     "title": "Network Queue Size on Execution Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 164 },
     "targets": [
      {
       "expr": "avg by (num)(network_queue_message_queue_size{network=\"$network\", role=\"execution\"})",
       "legendFormat": "execution-{{num}}"
      }
     ]
    },
    {
     "title": "Network Queue Size on Consensus Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 172 },
     "targets": [
      {
       "expr": "avg by (num)(network_queue_message_queue_size{network=\"$network\", role=\"consensus\"})",
       "legendFormat": "consensus-{{num}}"
      }
     ]
    },
    {
     "title": "Average Traffic Amplification ",
     "type": "timeseries",
     "description": "Average bytes transmitted over received.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 172 },
     "targets": [
      {
       "expr": "(avg by (role) (rate(node_network_transmit_bytes_total{network=\"$network\", role!=\"loader\", role!=\"tracing\"}[5m]))) \n/ \n(avg by (role) (rate(node_network_receive_bytes_total{network=\"$network\", role!=\"loader\", role!=\"tracing\"}[5m]))) "
      }
     ]
    }
   ]
  }
 ]
}