{
 "title": "Execution Data Sync",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "latest", "query": "localnet" },
   { "name": "network", "query": "localnet" }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EN - Data Sent (Last 30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(network_bitswap_data_sent{network=\"localnet\", role=\"execution\"}[30d])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "AN - Data Sent (Last 30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(network_bitswap_data_sent{network=\"localnet\",role=\"access\"}[30d])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "EN - Data Received (Last 30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(network_bitswap_data_received{network=\"localnet\",role=\"execution\"}[30d])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "AN - Data Received (Last 30d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(network_bitswap_data_received{network=\"localnet\",role=\"access\"}[30d])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  { "title": "Execution Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Execution Data Blob Tree Size - by quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(execution_data_sync_provider_execution_data_sizes_bytes{network=\"localnet\", role=\"execution\"})by(quantile)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of Chunks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(execution_data_sync_provider_number_of_chunks_bucket{network=\"localnet\"}[$__rate_interval])) by (le))",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Add Blobs Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "execution_data_sync_provider_add_blobs_durations_ms{network=\"localnet\", role=\"execution\", quantile=\"0.99\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Compute Root CID Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "execution_data_sync_provider_compute_root_id_durations_ms{network=\"localnet\", role=\"execution\", quantile=\"0.99\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Add Blobs Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(execution_data_sync_provider_add_blobs_failed{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Sealed Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "execution_runtime_last_executed_block_height{network=\"localnet\",role=\"execution\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  { "title": "Access Nodes - Requester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(state_synchronization_execution_data_requester_execution_requester_download_duration_ms_count{network=\"localnet\"}[$__rate_interval])-rate(state_synchronization_execution_data_requester_execution_data_failed_downloads_total{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "success - {{role}}-{{num}}"
    },
    {
     "expr": "rate(state_synchronization_execution_data_requester_execution_data_failed_downloads_total{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "fail - {{role}}-{{num}}"
    },
    {
     "expr": "rate(state_synchronization_execution_data_requester_execution_requester_download_retries_total{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "retry - {{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Requester - Download Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(increase(state_synchronization_execution_data_requester_execution_requester_download_duration_ms_bucket{network=\"localnet\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Unsent Notifications",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_synchronization_execution_data_requester_execution_requester_outstanding_notifications{network=\"localnet\",role=\"access\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Downloads in Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "state_synchronization_execution_data_requester_execution_requester_in_progress_downloads{network=\"localnet\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Downloaded Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "state_synchronization_execution_data_requester_execution_requester_highest_download_height{network=\"localnet\",role=\"access\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Blocks Behind Sealed - Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "clamp_min(sum(consensus_compliance_sealed_height{network=\"localnet\",role=\"access\"}) by (num) - sum(state_synchronization_execution_data_requester_execution_requester_highest_notification_height{network=\"localnet\",role=\"access\"}) by (num),0)",
     "legendFormat": "access-{{num}}"
    }
   ]
  },
  {
   "title": "Sealed Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consensus_compliance_sealed_height{network=\"localnet\",role=\"access\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Blocks Behind Sealed - Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "clamp_min(consensus_compliance_sealed_height{network=\"localnet\",role=\"access\"} - state_synchronization_execution_data_requester_execution_requester_highest_download_height{network=\"localnet\",role=\"access\"}, 0)",
     "legendFormat": "access-{{num}}"
    }
   ]
  },
  { "title": "Bitswap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Data Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(network_bitswap_data_sent{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Data Sent (Last 30d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(network_bitswap_data_sent{network=\"localnet\"}[30d])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(network_bitswap_data_received{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Data Received (Last 30d)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(network_bitswap_data_received{network=\"localnet\"}[30d])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Blobs Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "rate(network_bitswap_blobs_sent{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Blobs Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "rate(network_bitswap_blobs_received{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Duplicate Blobs Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rate(network_bitswap_dup_blobs_received{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Duplicate Data Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(network_bitswap_dup_data_received{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "rate(network_bitswap_messages_received{network=\"localnet\"}[$__rate_interval])",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "network_bitswap_num_peers{network=\"localnet\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Want List Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "network_bitswap_wantlist_size{network=\"localnet\"}",
     "legendFormat": "{{role}}-{{num}}"
    }
   ]
  },
  {
   "title": "Pruner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pruner Duration - EN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(execution_data_sync_pruner_prune_durations_ms{network=\"localnet\", role=\"execution\"}) by (num)",
       "legendFormat": "execution-{{num}}"
      }
     ]
    },
    {
     "title": "Pruned Height - EN",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "execution_data_sync_pruner_latest_height_pruned{network=\"localnet\", role=\"execution\"}",
       "legendFormat": "{{role}}-{{num}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Data Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Data - Add/Get in Progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "sum(state_synchronization_execution_data_service_execution_data_add_in_progress{network=\"localnet\", role=\"execution\"}) by (role)",
       "legendFormat": "Add ({{role}})"
      },
      {
       "expr": "sum(state_synchronization_execution_data_service_execution_data_get_in_progress{network=\"localnet\", role=\"access\"}) by (role)",
       "legendFormat": "Get ({{role}})"
      }
     ]
    },
    {
     "title": "Execution Data - Add/Get Failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "targets": [
      {
       "expr": "sum(rate(state_synchronization_execution_data_service_execution_data_add_fail_total{network=\"localnet\", role=\"execution\"}[$__rate_interval])) by(role)",
       "legendFormat": "Add ({{role}})"
      },
      {
       "expr": "sum(rate(state_synchronization_execution_data_service_execution_data_get_fail_total{network=\"localnet\", role=\"access\"}[$__rate_interval])) by(role)",
       "legendFormat": "Get ({{role}})"
      }
     ]
    },
    {
     "title": "Execution Data Add Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "sum(increase(state_synchronization_execution_data_service_execution_data_add_duration_ms_bucket{network=\"localnet\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Execution Data Get Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
     "targets": [
      {
       "expr": "sum(increase(state_synchronization_execution_data_service_execution_data_add_duration_ms_bucket{network=\"localnet\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc - Outdated",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blob Tree Size",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "sum(increase(state_synchronization_execution_data_service_execution_data_blob_tree_size_bucket{network=\"localnet\", role=\"execution\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Execution Data Add Latency",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "sum(increase(state_synchronization_execution_data_service_execution_data_add_duration_ms_bucket{network=\"localnet\", role=\"execution\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}