// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/onflow/flow-go/model/flow"
	"github.com/onflow/flow-go/model/verification"
	mock "github.com/stretchr/testify/mock"
)

// NewChunkStatuses creates a new instance of ChunkStatuses. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChunkStatuses(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChunkStatuses {
	mock := &ChunkStatuses{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ChunkStatuses is an autogenerated mock type for the ChunkStatuses type
type ChunkStatuses struct {
	mock.Mock
}

type ChunkStatuses_Expecter struct {
	mock *mock.Mock
}

func (_m *ChunkStatuses) EXPECT() *ChunkStatuses_Expecter {
	return &ChunkStatuses_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Add(identifier flow.Identifier, chunkStatus *verification.ChunkStatus) bool {
	ret := _mock.Called(identifier, chunkStatus)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier, *verification.ChunkStatus) bool); ok {
		r0 = returnFunc(identifier, chunkStatus)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ChunkStatuses_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type ChunkStatuses_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - identifier flow.Identifier
//   - chunkStatus *verification.ChunkStatus
func (_e *ChunkStatuses_Expecter) Add(identifier interface{}, chunkStatus interface{}) *ChunkStatuses_Add_Call {
	return &ChunkStatuses_Add_Call{Call: _e.mock.On("Add", identifier, chunkStatus)}
}

func (_c *ChunkStatuses_Add_Call) Run(run func(identifier flow.Identifier, chunkStatus *verification.ChunkStatus)) *ChunkStatuses_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Identifier
		if args[0] != nil {
			arg0 = args[0].(flow.Identifier)
		}
		var arg1 *verification.ChunkStatus
		if args[1] != nil {
			arg1 = args[1].(*verification.ChunkStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChunkStatuses_Add_Call) Return(b bool) *ChunkStatuses_Add_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ChunkStatuses_Add_Call) RunAndReturn(run func(identifier flow.Identifier, chunkStatus *verification.ChunkStatus) bool) *ChunkStatuses_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Adjust provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Adjust(key flow.Identifier, f func(*verification.ChunkStatus) *verification.ChunkStatus) (*verification.ChunkStatus, bool) {
	ret := _mock.Called(key, f)

	if len(ret) == 0 {
		panic("no return value specified for Adjust")
	}

	var r0 *verification.ChunkStatus
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier, func(*verification.ChunkStatus) *verification.ChunkStatus) (*verification.ChunkStatus, bool)); ok {
		return returnFunc(key, f)
	}
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier, func(*verification.ChunkStatus) *verification.ChunkStatus) *verification.ChunkStatus); ok {
		r0 = returnFunc(key, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*verification.ChunkStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(flow.Identifier, func(*verification.ChunkStatus) *verification.ChunkStatus) bool); ok {
		r1 = returnFunc(key, f)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ChunkStatuses_Adjust_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Adjust'
type ChunkStatuses_Adjust_Call struct {
	*mock.Call
}

// Adjust is a helper method to define mock.On call
//   - key flow.Identifier
//   - f func(*verification.ChunkStatus) *verification.ChunkStatus
func (_e *ChunkStatuses_Expecter) Adjust(key interface{}, f interface{}) *ChunkStatuses_Adjust_Call {
	return &ChunkStatuses_Adjust_Call{Call: _e.mock.On("Adjust", key, f)}
}

func (_c *ChunkStatuses_Adjust_Call) Run(run func(key flow.Identifier, f func(*verification.ChunkStatus) *verification.ChunkStatus)) *ChunkStatuses_Adjust_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Identifier
		if args[0] != nil {
			arg0 = args[0].(flow.Identifier)
		}
		var arg1 func(*verification.ChunkStatus) *verification.ChunkStatus
		if args[1] != nil {
			arg1 = args[1].(func(*verification.ChunkStatus) *verification.ChunkStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ChunkStatuses_Adjust_Call) Return(chunkStatus *verification.ChunkStatus, b bool) *ChunkStatuses_Adjust_Call {
	_c.Call.Return(chunkStatus, b)
	return _c
}

func (_c *ChunkStatuses_Adjust_Call) RunAndReturn(run func(key flow.Identifier, f func(*verification.ChunkStatus) *verification.ChunkStatus) (*verification.ChunkStatus, bool)) *ChunkStatuses_Adjust_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) All() map[flow.Identifier]*verification.ChunkStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 map[flow.Identifier]*verification.ChunkStatus
	if returnFunc, ok := ret.Get(0).(func() map[flow.Identifier]*verification.ChunkStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[flow.Identifier]*verification.ChunkStatus)
		}
	}
	return r0
}

// ChunkStatuses_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type ChunkStatuses_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *ChunkStatuses_Expecter) All() *ChunkStatuses_All_Call {
	return &ChunkStatuses_All_Call{Call: _e.mock.On("All")}
}

func (_c *ChunkStatuses_All_Call) Run(run func()) *ChunkStatuses_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChunkStatuses_All_Call) Return(identifierToChunkStatus map[flow.Identifier]*verification.ChunkStatus) *ChunkStatuses_All_Call {
	_c.Call.Return(identifierToChunkStatus)
	return _c
}

func (_c *ChunkStatuses_All_Call) RunAndReturn(run func() map[flow.Identifier]*verification.ChunkStatus) *ChunkStatuses_All_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Clear() {
	_mock.Called()
	return
}

// ChunkStatuses_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type ChunkStatuses_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *ChunkStatuses_Expecter) Clear() *ChunkStatuses_Clear_Call {
	return &ChunkStatuses_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *ChunkStatuses_Clear_Call) Run(run func()) *ChunkStatuses_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChunkStatuses_Clear_Call) Return() *ChunkStatuses_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *ChunkStatuses_Clear_Call) RunAndReturn(run func()) *ChunkStatuses_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Get(identifier flow.Identifier) (*verification.ChunkStatus, bool) {
	ret := _mock.Called(identifier)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *verification.ChunkStatus
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier) (*verification.ChunkStatus, bool)); ok {
		return returnFunc(identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier) *verification.ChunkStatus); ok {
		r0 = returnFunc(identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*verification.ChunkStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(flow.Identifier) bool); ok {
		r1 = returnFunc(identifier)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// ChunkStatuses_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ChunkStatuses_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - identifier flow.Identifier
func (_e *ChunkStatuses_Expecter) Get(identifier interface{}) *ChunkStatuses_Get_Call {
	return &ChunkStatuses_Get_Call{Call: _e.mock.On("Get", identifier)}
}

func (_c *ChunkStatuses_Get_Call) Run(run func(identifier flow.Identifier)) *ChunkStatuses_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Identifier
		if args[0] != nil {
			arg0 = args[0].(flow.Identifier)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChunkStatuses_Get_Call) Return(chunkStatus *verification.ChunkStatus, b bool) *ChunkStatuses_Get_Call {
	_c.Call.Return(chunkStatus, b)
	return _c
}

func (_c *ChunkStatuses_Get_Call) RunAndReturn(run func(identifier flow.Identifier) (*verification.ChunkStatus, bool)) *ChunkStatuses_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Has(identifier flow.Identifier) bool {
	ret := _mock.Called(identifier)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier) bool); ok {
		r0 = returnFunc(identifier)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ChunkStatuses_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type ChunkStatuses_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - identifier flow.Identifier
func (_e *ChunkStatuses_Expecter) Has(identifier interface{}) *ChunkStatuses_Has_Call {
	return &ChunkStatuses_Has_Call{Call: _e.mock.On("Has", identifier)}
}

func (_c *ChunkStatuses_Has_Call) Run(run func(identifier flow.Identifier)) *ChunkStatuses_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Identifier
		if args[0] != nil {
			arg0 = args[0].(flow.Identifier)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChunkStatuses_Has_Call) Return(b bool) *ChunkStatuses_Has_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ChunkStatuses_Has_Call) RunAndReturn(run func(identifier flow.Identifier) bool) *ChunkStatuses_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Remove(identifier flow.Identifier) bool {
	ret := _mock.Called(identifier)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(flow.Identifier) bool); ok {
		r0 = returnFunc(identifier)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// ChunkStatuses_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type ChunkStatuses_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - identifier flow.Identifier
func (_e *ChunkStatuses_Expecter) Remove(identifier interface{}) *ChunkStatuses_Remove_Call {
	return &ChunkStatuses_Remove_Call{Call: _e.mock.On("Remove", identifier)}
}

func (_c *ChunkStatuses_Remove_Call) Run(run func(identifier flow.Identifier)) *ChunkStatuses_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Identifier
		if args[0] != nil {
			arg0 = args[0].(flow.Identifier)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ChunkStatuses_Remove_Call) Return(b bool) *ChunkStatuses_Remove_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *ChunkStatuses_Remove_Call) RunAndReturn(run func(identifier flow.Identifier) bool) *ChunkStatuses_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Size() uint {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 uint
	if returnFunc, ok := ret.Get(0).(func() uint); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint)
	}
	return r0
}

// ChunkStatuses_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type ChunkStatuses_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *ChunkStatuses_Expecter) Size() *ChunkStatuses_Size_Call {
	return &ChunkStatuses_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *ChunkStatuses_Size_Call) Run(run func()) *ChunkStatuses_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChunkStatuses_Size_Call) Return(v uint) *ChunkStatuses_Size_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ChunkStatuses_Size_Call) RunAndReturn(run func() uint) *ChunkStatuses_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Values provides a mock function for the type ChunkStatuses
func (_mock *ChunkStatuses) Values() []*verification.ChunkStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 []*verification.ChunkStatus
	if returnFunc, ok := ret.Get(0).(func() []*verification.ChunkStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*verification.ChunkStatus)
		}
	}
	return r0
}

// ChunkStatuses_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type ChunkStatuses_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *ChunkStatuses_Expecter) Values() *ChunkStatuses_Values_Call {
	return &ChunkStatuses_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *ChunkStatuses_Values_Call) Run(run func()) *ChunkStatuses_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChunkStatuses_Values_Call) Return(chunkStatuss []*verification.ChunkStatus) *ChunkStatuses_Values_Call {
	_c.Call.Return(chunkStatuss)
	return _c
}

func (_c *ChunkStatuses_Values_Call) RunAndReturn(run func() []*verification.ChunkStatus) *ChunkStatuses_Values_Call {
	_c.Call.Return(run)
	return _c
}
