// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	cadence "github.com/onflow/cadence"

	flow "github.com/onflow/flow-go/model/flow"

	mock "github.com/stretchr/testify/mock"
)

// EventEmitter is an autogenerated mock type for the EventEmitter type
type EventEmitter struct {
	mock.Mock
}

// ConvertedServiceEvents provides a mock function with given fields:
func (_m *EventEmitter) ConvertedServiceEvents() flow.ServiceEventList {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConvertedServiceEvents")
	}

	var r0 flow.ServiceEventList
	if rf, ok := ret.Get(0).(func() flow.ServiceEventList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flow.ServiceEventList)
		}
	}

	return r0
}

// EmitEvent provides a mock function with given fields: event
func (_m *EventEmitter) EmitEvent(event cadence.Event) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for EmitEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(cadence.Event) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Events provides a mock function with given fields:
func (_m *EventEmitter) Events() flow.EventsList {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 flow.EventsList
	if rf, ok := ret.Get(0).(func() flow.EventsList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flow.EventsList)
		}
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *EventEmitter) Reset() {
	_m.Called()
}

// ServiceEvents provides a mock function with given fields:
func (_m *EventEmitter) ServiceEvents() flow.EventsList {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceEvents")
	}

	var r0 flow.EventsList
	if rf, ok := ret.Get(0).(func() flow.EventsList); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flow.EventsList)
		}
	}

	return r0
}

// NewEventEmitter creates a new instance of EventEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventEmitter {
	mock := &EventEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
