// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	"github.com/stretchr/testify/mock"

	"github.com/dapperlabs/flow-go/crypto/random"
	"github.com/dapperlabs/flow-go/model/chunkassignment"
	"github.com/dapperlabs/flow-go/model/flow"
)

// ChunkAssigner is an autogenerated mock type for the ChunkAssigner type
type ChunkAssigner struct {
	mock.Mock
}

// Assign provides a mock function with given fields: ids, chunks, rng
func (_m *ChunkAssigner) Assign(ids flow.IdentityList, chunks flow.ChunkList, rng random.Rand) (*chunkassignment.Assignment, error) {
	ret := _m.Called(ids, chunks, rng)

	var r0 *chunkassignment.Assignment
	if rf, ok := ret.Get(0).(func(flow.IdentityList, flow.ChunkList, random.Rand) *chunkassignment.Assignment); ok {
		r0 = rf(ids, chunks, rng)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chunkassignment.Assignment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(flow.IdentityList, flow.ChunkList, random.Rand) error); ok {
		r1 = rf(ids, chunks, rng)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
