// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// NewRegisterUpdatesHolder creates a new instance of RegisterUpdatesHolder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterUpdatesHolder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterUpdatesHolder {
	mock := &RegisterUpdatesHolder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RegisterUpdatesHolder is an autogenerated mock type for the RegisterUpdatesHolder type
type RegisterUpdatesHolder struct {
	mock.Mock
}

type RegisterUpdatesHolder_Expecter struct {
	mock *mock.Mock
}

func (_m *RegisterUpdatesHolder) EXPECT() *RegisterUpdatesHolder_Expecter {
	return &RegisterUpdatesHolder_Expecter{mock: &_m.Mock}
}

// UpdatedRegisterSet provides a mock function for the type RegisterUpdatesHolder
func (_mock *RegisterUpdatesHolder) UpdatedRegisterSet() map[flow.RegisterID]flow.RegisterValue {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdatedRegisterSet")
	}

	var r0 map[flow.RegisterID]flow.RegisterValue
	if returnFunc, ok := ret.Get(0).(func() map[flow.RegisterID]flow.RegisterValue); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[flow.RegisterID]flow.RegisterValue)
		}
	}
	return r0
}

// RegisterUpdatesHolder_UpdatedRegisterSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatedRegisterSet'
type RegisterUpdatesHolder_UpdatedRegisterSet_Call struct {
	*mock.Call
}

// UpdatedRegisterSet is a helper method to define mock.On call
func (_e *RegisterUpdatesHolder_Expecter) UpdatedRegisterSet() *RegisterUpdatesHolder_UpdatedRegisterSet_Call {
	return &RegisterUpdatesHolder_UpdatedRegisterSet_Call{Call: _e.mock.On("UpdatedRegisterSet")}
}

func (_c *RegisterUpdatesHolder_UpdatedRegisterSet_Call) Run(run func()) *RegisterUpdatesHolder_UpdatedRegisterSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegisterUpdatesHolder_UpdatedRegisterSet_Call) Return(registerIDToV map[flow.RegisterID]flow.RegisterValue) *RegisterUpdatesHolder_UpdatedRegisterSet_Call {
	_c.Call.Return(registerIDToV)
	return _c
}

func (_c *RegisterUpdatesHolder_UpdatedRegisterSet_Call) RunAndReturn(run func() map[flow.RegisterID]flow.RegisterValue) *RegisterUpdatesHolder_UpdatedRegisterSet_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatedRegisters provides a mock function for the type RegisterUpdatesHolder
func (_mock *RegisterUpdatesHolder) UpdatedRegisters() flow.RegisterEntries {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdatedRegisters")
	}

	var r0 flow.RegisterEntries
	if returnFunc, ok := ret.Get(0).(func() flow.RegisterEntries); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flow.RegisterEntries)
		}
	}
	return r0
}

// RegisterUpdatesHolder_UpdatedRegisters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatedRegisters'
type RegisterUpdatesHolder_UpdatedRegisters_Call struct {
	*mock.Call
}

// UpdatedRegisters is a helper method to define mock.On call
func (_e *RegisterUpdatesHolder_Expecter) UpdatedRegisters() *RegisterUpdatesHolder_UpdatedRegisters_Call {
	return &RegisterUpdatesHolder_UpdatedRegisters_Call{Call: _e.mock.On("UpdatedRegisters")}
}

func (_c *RegisterUpdatesHolder_UpdatedRegisters_Call) Run(run func()) *RegisterUpdatesHolder_UpdatedRegisters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RegisterUpdatesHolder_UpdatedRegisters_Call) Return(registerEntries flow.RegisterEntries) *RegisterUpdatesHolder_UpdatedRegisters_Call {
	_c.Call.Return(registerEntries)
	return _c
}

func (_c *RegisterUpdatesHolder_UpdatedRegisters_Call) RunAndReturn(run func() flow.RegisterEntries) *RegisterUpdatesHolder_UpdatedRegisters_Call {
	_c.Call.Return(run)
	return _c
}
