// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/observation/observation.proto

package observation

import (
	context "context"
	fmt "fmt"
	entities "github.com/dapperlabs/flow-go/protobuf/sdk/entities"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type SendTransactionRequest struct {
	Transaction          *entities.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{2}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTransaction() *entities.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type SendTransactionResponse struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionResponse) Reset()         { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()    {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{3}
}

func (m *SendTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionResponse.Unmarshal(m, b)
}
func (m *SendTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SendTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionResponse.Merge(m, src)
}
func (m *SendTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SendTransactionResponse.Size(m)
}
func (m *SendTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionResponse proto.InternalMessageInfo

func (m *SendTransactionResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetLatestBlockRequest struct {
	IsSealed             bool     `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestBlockRequest) Reset()         { *m = GetLatestBlockRequest{} }
func (m *GetLatestBlockRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestBlockRequest) ProtoMessage()    {}
func (*GetLatestBlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{4}
}

func (m *GetLatestBlockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestBlockRequest.Unmarshal(m, b)
}
func (m *GetLatestBlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestBlockRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestBlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestBlockRequest.Merge(m, src)
}
func (m *GetLatestBlockRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestBlockRequest.Size(m)
}
func (m *GetLatestBlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestBlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestBlockRequest proto.InternalMessageInfo

func (m *GetLatestBlockRequest) GetIsSealed() bool {
	if m != nil {
		return m.IsSealed
	}
	return false
}

type GetBlockByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByIDRequest) Reset()         { *m = GetBlockByIDRequest{} }
func (m *GetBlockByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByIDRequest) ProtoMessage()    {}
func (*GetBlockByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{5}
}

func (m *GetBlockByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByIDRequest.Unmarshal(m, b)
}
func (m *GetBlockByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByIDRequest.Merge(m, src)
}
func (m *GetBlockByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByIDRequest.Size(m)
}
func (m *GetBlockByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByIDRequest proto.InternalMessageInfo

func (m *GetBlockByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHeightRequest) Reset()         { *m = GetBlockByHeightRequest{} }
func (m *GetBlockByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHeightRequest) ProtoMessage()    {}
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{6}
}

func (m *GetBlockByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHeightRequest.Merge(m, src)
}
func (m *GetBlockByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHeightRequest.Size(m)
}
func (m *GetBlockByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHeightRequest proto.InternalMessageInfo

func (m *GetBlockByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockResponse struct {
	Block                *entities.BlockHeader `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{7}
}

func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockResponse.Unmarshal(m, b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockResponse.Marshal(b, m, deterministic)
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return xxx_messageInfo_BlockResponse.Size(m)
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetBlock() *entities.BlockHeader {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetLatestBlockDetailsRequest struct {
	IsSealed             bool     `protobuf:"varint,1,opt,name=is_sealed,json=isSealed,proto3" json:"is_sealed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestBlockDetailsRequest) Reset()         { *m = GetLatestBlockDetailsRequest{} }
func (m *GetLatestBlockDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestBlockDetailsRequest) ProtoMessage()    {}
func (*GetLatestBlockDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{8}
}

func (m *GetLatestBlockDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestBlockDetailsRequest.Unmarshal(m, b)
}
func (m *GetLatestBlockDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestBlockDetailsRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestBlockDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestBlockDetailsRequest.Merge(m, src)
}
func (m *GetLatestBlockDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestBlockDetailsRequest.Size(m)
}
func (m *GetLatestBlockDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestBlockDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestBlockDetailsRequest proto.InternalMessageInfo

func (m *GetLatestBlockDetailsRequest) GetIsSealed() bool {
	if m != nil {
		return m.IsSealed
	}
	return false
}

type GetBlockDetailsByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockDetailsByIDRequest) Reset()         { *m = GetBlockDetailsByIDRequest{} }
func (m *GetBlockDetailsByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockDetailsByIDRequest) ProtoMessage()    {}
func (*GetBlockDetailsByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{9}
}

func (m *GetBlockDetailsByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockDetailsByIDRequest.Unmarshal(m, b)
}
func (m *GetBlockDetailsByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockDetailsByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockDetailsByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockDetailsByIDRequest.Merge(m, src)
}
func (m *GetBlockDetailsByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockDetailsByIDRequest.Size(m)
}
func (m *GetBlockDetailsByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockDetailsByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockDetailsByIDRequest proto.InternalMessageInfo

func (m *GetBlockDetailsByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetBlockDetailsByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockDetailsByHeightRequest) Reset()         { *m = GetBlockDetailsByHeightRequest{} }
func (m *GetBlockDetailsByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockDetailsByHeightRequest) ProtoMessage()    {}
func (*GetBlockDetailsByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{10}
}

func (m *GetBlockDetailsByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockDetailsByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockDetailsByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockDetailsByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockDetailsByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockDetailsByHeightRequest.Merge(m, src)
}
func (m *GetBlockDetailsByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockDetailsByHeightRequest.Size(m)
}
func (m *GetBlockDetailsByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockDetailsByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockDetailsByHeightRequest proto.InternalMessageInfo

func (m *GetBlockDetailsByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockDetailsResponse struct {
	Block                *entities.Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *BlockDetailsResponse) Reset()         { *m = BlockDetailsResponse{} }
func (m *BlockDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*BlockDetailsResponse) ProtoMessage()    {}
func (*BlockDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{11}
}

func (m *BlockDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockDetailsResponse.Unmarshal(m, b)
}
func (m *BlockDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockDetailsResponse.Marshal(b, m, deterministic)
}
func (m *BlockDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockDetailsResponse.Merge(m, src)
}
func (m *BlockDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_BlockDetailsResponse.Size(m)
}
func (m *BlockDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockDetailsResponse proto.InternalMessageInfo

func (m *BlockDetailsResponse) GetBlock() *entities.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetCollectionByIDRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollectionByIDRequest) Reset()         { *m = GetCollectionByIDRequest{} }
func (m *GetCollectionByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollectionByIDRequest) ProtoMessage()    {}
func (*GetCollectionByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{12}
}

func (m *GetCollectionByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollectionByIDRequest.Unmarshal(m, b)
}
func (m *GetCollectionByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollectionByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetCollectionByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollectionByIDRequest.Merge(m, src)
}
func (m *GetCollectionByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollectionByIDRequest.Size(m)
}
func (m *GetCollectionByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollectionByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollectionByIDRequest proto.InternalMessageInfo

func (m *GetCollectionByIDRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetCollectionByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollectionByHeightRequest) Reset()         { *m = GetCollectionByHeightRequest{} }
func (m *GetCollectionByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollectionByHeightRequest) ProtoMessage()    {}
func (*GetCollectionByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{13}
}

func (m *GetCollectionByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollectionByHeightRequest.Unmarshal(m, b)
}
func (m *GetCollectionByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollectionByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetCollectionByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollectionByHeightRequest.Merge(m, src)
}
func (m *GetCollectionByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollectionByHeightRequest.Size(m)
}
func (m *GetCollectionByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollectionByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollectionByHeightRequest proto.InternalMessageInfo

func (m *GetCollectionByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type CollectionResponse struct {
	Collection           *entities.Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CollectionResponse) Reset()         { *m = CollectionResponse{} }
func (m *CollectionResponse) String() string { return proto.CompactTextString(m) }
func (*CollectionResponse) ProtoMessage()    {}
func (*CollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{14}
}

func (m *CollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectionResponse.Unmarshal(m, b)
}
func (m *CollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectionResponse.Marshal(b, m, deterministic)
}
func (m *CollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectionResponse.Merge(m, src)
}
func (m *CollectionResponse) XXX_Size() int {
	return xxx_messageInfo_CollectionResponse.Size(m)
}
func (m *CollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectionResponse proto.InternalMessageInfo

func (m *CollectionResponse) GetCollection() *entities.Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

type GetAccountRequest struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{15}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type GetAccountResponse struct {
	Account              *entities.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{16}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *entities.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ExecuteScriptRequest struct {
	Script               []byte   `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptRequest) Reset()         { *m = ExecuteScriptRequest{} }
func (m *ExecuteScriptRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptRequest) ProtoMessage()    {}
func (*ExecuteScriptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{17}
}

func (m *ExecuteScriptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptRequest.Unmarshal(m, b)
}
func (m *ExecuteScriptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptRequest.Merge(m, src)
}
func (m *ExecuteScriptRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptRequest.Size(m)
}
func (m *ExecuteScriptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptRequest proto.InternalMessageInfo

func (m *ExecuteScriptRequest) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type ExecuteScriptResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteScriptResponse) Reset()         { *m = ExecuteScriptResponse{} }
func (m *ExecuteScriptResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteScriptResponse) ProtoMessage()    {}
func (*ExecuteScriptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{18}
}

func (m *ExecuteScriptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteScriptResponse.Unmarshal(m, b)
}
func (m *ExecuteScriptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteScriptResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteScriptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScriptResponse.Merge(m, src)
}
func (m *ExecuteScriptResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteScriptResponse.Size(m)
}
func (m *ExecuteScriptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScriptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScriptResponse proto.InternalMessageInfo

func (m *ExecuteScriptResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetEventsRequest struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	StartBlock           uint64   `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock             uint64   `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{19}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

func (m *GetEventsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetEventsRequest) GetStartBlock() uint64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *GetEventsRequest) GetEndBlock() uint64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

type GetEventsResponse struct {
	Events               []*entities.Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEventsResponse) Reset()         { *m = GetEventsResponse{} }
func (m *GetEventsResponse) String() string { return proto.CompactTextString(m) }
func (*GetEventsResponse) ProtoMessage()    {}
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{20}
}

func (m *GetEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsResponse.Unmarshal(m, b)
}
func (m *GetEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsResponse.Marshal(b, m, deterministic)
}
func (m *GetEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsResponse.Merge(m, src)
}
func (m *GetEventsResponse) XXX_Size() int {
	return xxx_messageInfo_GetEventsResponse.Size(m)
}
func (m *GetEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsResponse proto.InternalMessageInfo

func (m *GetEventsResponse) GetEvents() []*entities.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetTransactionRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTransactionRequest) Reset()         { *m = GetTransactionRequest{} }
func (m *GetTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*GetTransactionRequest) ProtoMessage()    {}
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{21}
}

func (m *GetTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionRequest.Unmarshal(m, b)
}
func (m *GetTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionRequest.Marshal(b, m, deterministic)
}
func (m *GetTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionRequest.Merge(m, src)
}
func (m *GetTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_GetTransactionRequest.Size(m)
}
func (m *GetTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionRequest proto.InternalMessageInfo

func (m *GetTransactionRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetTransactionResponse struct {
	Transaction          *entities.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Events               []*entities.Event     `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetTransactionResponse) Reset()         { *m = GetTransactionResponse{} }
func (m *GetTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionResponse) ProtoMessage()    {}
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{22}
}

func (m *GetTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionResponse.Unmarshal(m, b)
}
func (m *GetTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionResponse.Merge(m, src)
}
func (m *GetTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionResponse.Size(m)
}
func (m *GetTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionResponse proto.InternalMessageInfo

func (m *GetTransactionResponse) GetTransaction() *entities.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *GetTransactionResponse) GetEvents() []*entities.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetTransactionStatusResponse struct {
	Status               entities.TransactionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=flow.sdk.entities.TransactionStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetTransactionStatusResponse) Reset()         { *m = GetTransactionStatusResponse{} }
func (m *GetTransactionStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetTransactionStatusResponse) ProtoMessage()    {}
func (*GetTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f8771b9f9d71bac, []int{23}
}

func (m *GetTransactionStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTransactionStatusResponse.Unmarshal(m, b)
}
func (m *GetTransactionStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTransactionStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetTransactionStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTransactionStatusResponse.Merge(m, src)
}
func (m *GetTransactionStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetTransactionStatusResponse.Size(m)
}
func (m *GetTransactionStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTransactionStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTransactionStatusResponse proto.InternalMessageInfo

func (m *GetTransactionStatusResponse) GetStatus() entities.TransactionStatus {
	if m != nil {
		return m.Status
	}
	return entities.TransactionStatus_STATUS_UNKNOWN
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "flow.services.observation.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "flow.services.observation.PingResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "flow.services.observation.SendTransactionRequest")
	proto.RegisterType((*SendTransactionResponse)(nil), "flow.services.observation.SendTransactionResponse")
	proto.RegisterType((*GetLatestBlockRequest)(nil), "flow.services.observation.GetLatestBlockRequest")
	proto.RegisterType((*GetBlockByIDRequest)(nil), "flow.services.observation.GetBlockByIDRequest")
	proto.RegisterType((*GetBlockByHeightRequest)(nil), "flow.services.observation.GetBlockByHeightRequest")
	proto.RegisterType((*BlockResponse)(nil), "flow.services.observation.BlockResponse")
	proto.RegisterType((*GetLatestBlockDetailsRequest)(nil), "flow.services.observation.GetLatestBlockDetailsRequest")
	proto.RegisterType((*GetBlockDetailsByIDRequest)(nil), "flow.services.observation.GetBlockDetailsByIDRequest")
	proto.RegisterType((*GetBlockDetailsByHeightRequest)(nil), "flow.services.observation.GetBlockDetailsByHeightRequest")
	proto.RegisterType((*BlockDetailsResponse)(nil), "flow.services.observation.BlockDetailsResponse")
	proto.RegisterType((*GetCollectionByIDRequest)(nil), "flow.services.observation.GetCollectionByIDRequest")
	proto.RegisterType((*GetCollectionByHeightRequest)(nil), "flow.services.observation.GetCollectionByHeightRequest")
	proto.RegisterType((*CollectionResponse)(nil), "flow.services.observation.CollectionResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "flow.services.observation.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "flow.services.observation.GetAccountResponse")
	proto.RegisterType((*ExecuteScriptRequest)(nil), "flow.services.observation.ExecuteScriptRequest")
	proto.RegisterType((*ExecuteScriptResponse)(nil), "flow.services.observation.ExecuteScriptResponse")
	proto.RegisterType((*GetEventsRequest)(nil), "flow.services.observation.GetEventsRequest")
	proto.RegisterType((*GetEventsResponse)(nil), "flow.services.observation.GetEventsResponse")
	proto.RegisterType((*GetTransactionRequest)(nil), "flow.services.observation.GetTransactionRequest")
	proto.RegisterType((*GetTransactionResponse)(nil), "flow.services.observation.GetTransactionResponse")
	proto.RegisterType((*GetTransactionStatusResponse)(nil), "flow.services.observation.GetTransactionStatusResponse")
}

func init() {
	proto.RegisterFile("services/observation/observation.proto", fileDescriptor_2f8771b9f9d71bac)
}

var fileDescriptor_2f8771b9f9d71bac = []byte{
	// 860 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xef, 0x4f, 0xdb, 0x46,
	0x18, 0x56, 0x02, 0x04, 0x78, 0x43, 0xb2, 0xed, 0x16, 0x20, 0x33, 0x1b, 0x43, 0xd6, 0x06, 0x6c,
	0x03, 0x03, 0x81, 0x8d, 0x4d, 0xdb, 0xa4, 0x96, 0x92, 0x86, 0x56, 0x95, 0x5a, 0x25, 0x95, 0x2a,
	0xa1, 0x4a, 0xc8, 0xd8, 0x2f, 0x60, 0x61, 0xd9, 0xa9, 0xef, 0xc2, 0x8f, 0x0f, 0x55, 0xd5, 0x0f,
	0xfd, 0xd6, 0x3f, 0xb7, 0x7f, 0x40, 0x95, 0xf3, 0xd9, 0x3e, 0x3b, 0x8e, 0x63, 0xb7, 0xdf, 0x7c,
	0x6f, 0x9e, 0xe7, 0xde, 0xe7, 0xbd, 0x1f, 0xef, 0x73, 0x81, 0x75, 0x8a, 0xde, 0x8d, 0x65, 0x20,
	0xdd, 0x71, 0xcf, 0x87, 0x9f, 0x3a, 0xb3, 0x5c, 0x47, 0xfe, 0xd6, 0xfa, 0x9e, 0xcb, 0x5c, 0xf2,
	0xc3, 0x85, 0xed, 0xde, 0x6a, 0x01, 0x58, 0x93, 0x00, 0xca, 0x0a, 0x35, 0xaf, 0x77, 0xd0, 0x61,
	0x16, 0xb3, 0x90, 0x86, 0x1f, 0x3e, 0x4f, 0xad, 0x41, 0xf5, 0x85, 0xe5, 0x5c, 0x76, 0xf1, 0xcd,
	0x00, 0x29, 0x53, 0x37, 0x61, 0xc1, 0x1f, 0xd2, 0xbe, 0xeb, 0x50, 0x24, 0x4d, 0x98, 0xd5, 0x4d,
	0xd3, 0x43, 0x4a, 0x9b, 0xa5, 0xb5, 0xd2, 0xe6, 0x42, 0x37, 0x18, 0xaa, 0xa7, 0xb0, 0xd4, 0x43,
	0xc7, 0x7c, 0xe9, 0xe9, 0x0e, 0xd5, 0x8d, 0x61, 0x22, 0x31, 0x07, 0x79, 0x00, 0x55, 0x16, 0x45,
	0x39, 0xaf, 0xda, 0x5a, 0xd5, 0x7c, 0x81, 0xe6, 0xb5, 0x16, 0x2a, 0x90, 0xb9, 0x32, 0x45, 0xfd,
	0x0d, 0x96, 0x47, 0xe6, 0x16, 0x82, 0xea, 0x50, 0xb6, 0x4c, 0xa1, 0xa5, 0x6c, 0x99, 0xea, 0x01,
	0x2c, 0x76, 0x90, 0x3d, 0xd3, 0x19, 0x52, 0x76, 0x64, 0xbb, 0xc6, 0x75, 0xa0, 0x62, 0x05, 0xe6,
	0x2d, 0x7a, 0x46, 0x51, 0xb7, 0xd1, 0xc7, 0xcf, 0x75, 0xe7, 0x2c, 0xda, 0xe3, 0x63, 0xf5, 0x57,
	0xf8, 0xbe, 0x83, 0x3e, 0xfe, 0xe8, 0xfe, 0xc9, 0x71, 0xc0, 0x49, 0x4e, 0xbe, 0x07, 0xcb, 0x11,
	0xec, 0x04, 0xad, 0xcb, 0x2b, 0x16, 0x40, 0x97, 0xa0, 0x72, 0xc5, 0x03, 0x1c, 0x3e, 0xdd, 0x15,
	0x23, 0xb5, 0x0d, 0x35, 0x21, 0x43, 0x08, 0x3e, 0x80, 0x99, 0xf3, 0x61, 0x20, 0x63, 0x1d, 0x38,
	0xe1, 0x04, 0x75, 0x13, 0xbd, 0xae, 0x0f, 0x56, 0xff, 0x85, 0x1f, 0xe3, 0x65, 0x1d, 0x23, 0xd3,
	0x2d, 0x9b, 0xe6, 0xaa, 0x6e, 0x0b, 0x94, 0x40, 0xb6, 0xa0, 0x65, 0x15, 0xf9, 0x37, 0xac, 0x8e,
	0xa0, 0xf3, 0xd5, 0xfa, 0x18, 0x1a, 0x71, 0x6d, 0xa2, 0x64, 0x2d, 0x5e, 0x72, 0x73, 0x5c, 0xc9,
	0x41, 0xb1, 0xbf, 0x43, 0xb3, 0x83, 0xec, 0x91, 0x6b, 0xdb, 0xc8, 0x37, 0x3b, 0x4b, 0xed, 0x5f,
	0x7c, 0x61, 0x64, 0x6c, 0x3e, 0xad, 0x3d, 0x20, 0x11, 0x29, 0x54, 0xfa, 0x3f, 0x80, 0x11, 0x46,
	0x85, 0xdc, 0x9f, 0x52, 0xe4, 0x4a, 0x54, 0x89, 0xa0, 0x6e, 0xc3, 0x77, 0x1d, 0x64, 0x0f, 0x0d,
	0xc3, 0x1d, 0x38, 0xa1, 0x82, 0xf1, 0x57, 0xe6, 0x29, 0x10, 0x19, 0x1e, 0x1e, 0x90, 0x59, 0xdd,
	0x0f, 0x09, 0x01, 0x4a, 0x8a, 0x80, 0x80, 0x14, 0x40, 0x55, 0x0d, 0x1a, 0xed, 0x3b, 0x34, 0x06,
	0x0c, 0x7b, 0x86, 0x67, 0xf5, 0xe5, 0xfa, 0x29, 0x0f, 0x88, 0xe4, 0x62, 0xa4, 0x6e, 0xc3, 0x62,
	0x02, 0x2f, 0xd2, 0x37, 0x60, 0xe6, 0x46, 0xb7, 0x07, 0x28, 0xf0, 0xfe, 0x40, 0x35, 0xe1, 0xdb,
	0x0e, 0xb2, 0xf6, 0x0d, 0x3a, 0x2c, 0x3c, 0x73, 0x04, 0xa6, 0xd9, 0x7d, 0xdf, 0x07, 0xce, 0x77,
	0xf9, 0x37, 0xf9, 0x19, 0xaa, 0x94, 0xe9, 0x1e, 0x3b, 0xf3, 0x37, 0xbc, 0xcc, 0xd7, 0x1c, 0x78,
	0x88, 0x6f, 0xf1, 0xf0, 0xa0, 0xa2, 0x63, 0x8a, 0x9f, 0xa7, 0xf8, 0xcf, 0x73, 0xe8, 0x98, 0xfc,
	0x47, 0xb5, 0xcd, 0xd7, 0x2f, 0xc8, 0x22, 0x04, 0xed, 0x42, 0x05, 0x79, 0xa4, 0x59, 0x5a, 0x9b,
	0x1a, 0x73, 0x7c, 0x38, 0xa5, 0x2b, 0x70, 0xea, 0x06, 0xef, 0x01, 0x29, 0x9d, 0x28, 0x79, 0x78,
	0x3e, 0x96, 0x60, 0x29, 0x89, 0x14, 0x59, 0xbf, 0xba, 0x69, 0x49, 0xba, 0xcb, 0x39, 0x75, 0xbf,
	0xe6, 0x67, 0x59, 0x9a, 0xb0, 0xc7, 0x74, 0x36, 0x88, 0x56, 0xe2, 0x3f, 0xa8, 0x50, 0x1e, 0xe1,
	0x72, 0xea, 0xad, 0x5f, 0xb2, 0xe5, 0x08, 0xb6, 0xe0, 0xb4, 0x3e, 0xd5, 0xa0, 0xfe, 0x9c, 0xdb,
	0x00, 0xf6, 0x7c, 0x5b, 0x20, 0xaf, 0x60, 0x7a, 0xd8, 0xdd, 0xc9, 0xba, 0x36, 0xd6, 0x2d, 0x34,
	0xc9, 0x0d, 0x94, 0x8d, 0x89, 0x38, 0xa1, 0xd4, 0x86, 0x7a, 0xbc, 0x5d, 0x91, 0xdd, 0x0c, 0x6a,
	0x6a, 0xc3, 0x56, 0x36, 0x33, 0x18, 0xf1, 0x96, 0x7a, 0x05, 0x0b, 0x72, 0xf7, 0x26, 0x5a, 0x76,
	0xae, 0x64, 0x9b, 0x2f, 0x90, 0xa9, 0xcf, 0xaf, 0x41, 0xcc, 0x00, 0x48, 0x2b, 0x57, 0xb6, 0x58,
	0x57, 0x2a, 0x90, 0xf1, 0x7d, 0x29, 0x69, 0x68, 0xa2, 0xbb, 0x92, 0xc3, 0xdc, 0x2b, 0x1a, 0xf7,
	0x0a, 0x65, 0x67, 0x52, 0xf2, 0x64, 0xff, 0x7e, 0x1b, 0xb9, 0xa3, 0xe4, 0x1f, 0xe4, 0xcf, 0x1c,
	0x85, 0x8f, 0xfa, 0x4d, 0xf1, 0xf4, 0x1f, 0x4a, 0x91, 0xed, 0x26, 0x1c, 0x89, 0xfc, 0x53, 0x44,
	0x43, 0x7c, 0x0f, 0x0a, 0xeb, 0xb8, 0xe5, 0xdd, 0x29, 0x6e, 0x4b, 0x64, 0x3f, 0x5b, 0x40, 0xaa,
	0x89, 0x29, 0xdb, 0x19, 0xa4, 0x14, 0x57, 0x7a, 0xc7, 0x8f, 0xc0, 0xa8, 0xc7, 0x4d, 0x3a, 0x02,
	0x63, 0x5d, 0xb1, 0xa8, 0x80, 0x3b, 0xf8, 0x26, 0xf1, 0xfe, 0x22, 0x7b, 0x19, 0x33, 0xa4, 0xbf,
	0x03, 0x95, 0x56, 0x11, 0x8a, 0xc8, 0x3c, 0xe0, 0x8d, 0x44, 0x4e, 0x3c, 0xa1, 0x91, 0xa4, 0xe4,
	0xdd, 0x2b, 0xc0, 0x88, 0x6e, 0x5d, 0x23, 0xad, 0x15, 0x7f, 0x41, 0xf6, 0xc3, 0xdc, 0x8c, 0x44,
	0xb7, 0xb7, 0x00, 0xa2, 0xd7, 0x01, 0xd9, 0xca, 0x9e, 0x26, 0xfe, 0xe6, 0xc8, 0xdc, 0xdf, 0x94,
	0x27, 0x87, 0x07, 0xb5, 0xd8, 0x63, 0x80, 0x64, 0xdd, 0x8d, 0xb4, 0x67, 0x86, 0xb2, 0x9b, 0x9f,
	0x20, 0x72, 0x5e, 0xc0, 0x7c, 0xe8, 0xf5, 0xe4, 0x8f, 0x6c, 0xbd, 0xb1, 0x77, 0x87, 0xb2, 0x95,
	0x0f, 0xec, 0xe7, 0x39, 0xaa, 0x9d, 0x56, 0x25, 0xc0, 0x79, 0x85, 0xff, 0xcd, 0xd9, 0xff, 0x1c,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x28, 0x32, 0xff, 0x48, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObserveServiceClient is the client API for ObserveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObserveServiceClient interface {
	// Ping is used to check if the observation node is up
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Block (block header)
	// GetLatestBlock gets the latest sealed or unsealed block.
	GetLatestBlock(ctx context.Context, in *GetLatestBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// GetBlockByID gets a block by its ID
	GetBlockByID(ctx context.Context, in *GetBlockByIDRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// GetBlockByHeight gets a block by its height
	GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*BlockResponse, error)
	// Block details (block payload)
	// GetLatestBlockDetails gets the block details of the latest sealed or unsealed block.
	GetLatestBlockDetails(ctx context.Context, in *GetLatestBlockDetailsRequest, opts ...grpc.CallOption) (*BlockDetailsResponse, error)
	// GetBlockDetailsByID gets the block details by the block ID
	GetBlockDetailsByID(ctx context.Context, in *GetBlockDetailsByIDRequest, opts ...grpc.CallOption) (*BlockDetailsResponse, error)
	// GetBlockDetailsByHeight gets the block details by the block height
	GetBlockDetailsByHeight(ctx context.Context, in *GetBlockDetailsByHeightRequest, opts ...grpc.CallOption) (*BlockDetailsResponse, error)
	// Collection
	// GetCollectionByID gets a collection by its ID
	GetCollectionByID(ctx context.Context, in *GetCollectionByIDRequest, opts ...grpc.CallOption) (*CollectionResponse, error)
	// GetCollectionByHeight gets a collection by its height
	GetCollectionByHeight(ctx context.Context, in *GetCollectionByHeightRequest, opts ...grpc.CallOption) (*CollectionResponse, error)
	// Transaction
	// SendTransaction submits a transaction to the network.
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
	// GetTransactions gets a transaction by ID.
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	// GetTransactionStatus gets the statue of a transaction
	GetTransactionStatus(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error)
	// Account
	// GetAccount gets an account by address.
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	// Script
	// ExecuteScript executes a script against the latest sealed world state.
	ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error)
	// Events
	// GetEvents retrieves events matching a given query.
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error)
}

type observeServiceClient struct {
	cc *grpc.ClientConn
}

func NewObserveServiceClient(cc *grpc.ClientConn) ObserveServiceClient {
	return &observeServiceClient{cc}
}

func (c *observeServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetLatestBlock(ctx context.Context, in *GetLatestBlockRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetLatestBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetBlockByID(ctx context.Context, in *GetBlockByIDRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetBlockByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*BlockResponse, error) {
	out := new(BlockResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetLatestBlockDetails(ctx context.Context, in *GetLatestBlockDetailsRequest, opts ...grpc.CallOption) (*BlockDetailsResponse, error) {
	out := new(BlockDetailsResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetLatestBlockDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetBlockDetailsByID(ctx context.Context, in *GetBlockDetailsByIDRequest, opts ...grpc.CallOption) (*BlockDetailsResponse, error) {
	out := new(BlockDetailsResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetBlockDetailsByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetBlockDetailsByHeight(ctx context.Context, in *GetBlockDetailsByHeightRequest, opts ...grpc.CallOption) (*BlockDetailsResponse, error) {
	out := new(BlockDetailsResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetBlockDetailsByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetCollectionByID(ctx context.Context, in *GetCollectionByIDRequest, opts ...grpc.CallOption) (*CollectionResponse, error) {
	out := new(CollectionResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetCollectionByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetCollectionByHeight(ctx context.Context, in *GetCollectionByHeightRequest, opts ...grpc.CallOption) (*CollectionResponse, error) {
	out := new(CollectionResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetCollectionByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetTransactionStatus(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionStatusResponse, error) {
	out := new(GetTransactionStatusResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetTransactionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error) {
	out := new(ExecuteScriptResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/ExecuteScript", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeServiceClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*GetEventsResponse, error) {
	out := new(GetEventsResponse)
	err := c.cc.Invoke(ctx, "/flow.services.observation.ObserveService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObserveServiceServer is the server API for ObserveService service.
type ObserveServiceServer interface {
	// Ping is used to check if the observation node is up
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Block (block header)
	// GetLatestBlock gets the latest sealed or unsealed block.
	GetLatestBlock(context.Context, *GetLatestBlockRequest) (*BlockResponse, error)
	// GetBlockByID gets a block by its ID
	GetBlockByID(context.Context, *GetBlockByIDRequest) (*BlockResponse, error)
	// GetBlockByHeight gets a block by its height
	GetBlockByHeight(context.Context, *GetBlockByHeightRequest) (*BlockResponse, error)
	// Block details (block payload)
	// GetLatestBlockDetails gets the block details of the latest sealed or unsealed block.
	GetLatestBlockDetails(context.Context, *GetLatestBlockDetailsRequest) (*BlockDetailsResponse, error)
	// GetBlockDetailsByID gets the block details by the block ID
	GetBlockDetailsByID(context.Context, *GetBlockDetailsByIDRequest) (*BlockDetailsResponse, error)
	// GetBlockDetailsByHeight gets the block details by the block height
	GetBlockDetailsByHeight(context.Context, *GetBlockDetailsByHeightRequest) (*BlockDetailsResponse, error)
	// Collection
	// GetCollectionByID gets a collection by its ID
	GetCollectionByID(context.Context, *GetCollectionByIDRequest) (*CollectionResponse, error)
	// GetCollectionByHeight gets a collection by its height
	GetCollectionByHeight(context.Context, *GetCollectionByHeightRequest) (*CollectionResponse, error)
	// Transaction
	// SendTransaction submits a transaction to the network.
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
	// GetTransactions gets a transaction by ID.
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	// GetTransactionStatus gets the statue of a transaction
	GetTransactionStatus(context.Context, *GetTransactionRequest) (*GetTransactionStatusResponse, error)
	// Account
	// GetAccount gets an account by address.
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	// Script
	// ExecuteScript executes a script against the latest sealed world state.
	ExecuteScript(context.Context, *ExecuteScriptRequest) (*ExecuteScriptResponse, error)
	// Events
	// GetEvents retrieves events matching a given query.
	GetEvents(context.Context, *GetEventsRequest) (*GetEventsResponse, error)
}

// UnimplementedObserveServiceServer can be embedded to have forward compatible implementations.
type UnimplementedObserveServiceServer struct {
}

func (*UnimplementedObserveServiceServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedObserveServiceServer) GetLatestBlock(ctx context.Context, req *GetLatestBlockRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBlock not implemented")
}
func (*UnimplementedObserveServiceServer) GetBlockByID(ctx context.Context, req *GetBlockByIDRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByID not implemented")
}
func (*UnimplementedObserveServiceServer) GetBlockByHeight(ctx context.Context, req *GetBlockByHeightRequest) (*BlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByHeight not implemented")
}
func (*UnimplementedObserveServiceServer) GetLatestBlockDetails(ctx context.Context, req *GetLatestBlockDetailsRequest) (*BlockDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBlockDetails not implemented")
}
func (*UnimplementedObserveServiceServer) GetBlockDetailsByID(ctx context.Context, req *GetBlockDetailsByIDRequest) (*BlockDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockDetailsByID not implemented")
}
func (*UnimplementedObserveServiceServer) GetBlockDetailsByHeight(ctx context.Context, req *GetBlockDetailsByHeightRequest) (*BlockDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockDetailsByHeight not implemented")
}
func (*UnimplementedObserveServiceServer) GetCollectionByID(ctx context.Context, req *GetCollectionByIDRequest) (*CollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionByID not implemented")
}
func (*UnimplementedObserveServiceServer) GetCollectionByHeight(ctx context.Context, req *GetCollectionByHeightRequest) (*CollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionByHeight not implemented")
}
func (*UnimplementedObserveServiceServer) SendTransaction(ctx context.Context, req *SendTransactionRequest) (*SendTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedObserveServiceServer) GetTransaction(ctx context.Context, req *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedObserveServiceServer) GetTransactionStatus(ctx context.Context, req *GetTransactionRequest) (*GetTransactionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionStatus not implemented")
}
func (*UnimplementedObserveServiceServer) GetAccount(ctx context.Context, req *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (*UnimplementedObserveServiceServer) ExecuteScript(ctx context.Context, req *ExecuteScriptRequest) (*ExecuteScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScript not implemented")
}
func (*UnimplementedObserveServiceServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*GetEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterObserveServiceServer(s *grpc.Server, srv ObserveServiceServer) {
	s.RegisterService(&_ObserveService_serviceDesc, srv)
}

func _ObserveService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetLatestBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetLatestBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetLatestBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetLatestBlock(ctx, req.(*GetLatestBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetBlockByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetBlockByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetBlockByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetBlockByID(ctx, req.(*GetBlockByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetBlockByHeight(ctx, req.(*GetBlockByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetLatestBlockDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestBlockDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetLatestBlockDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetLatestBlockDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetLatestBlockDetails(ctx, req.(*GetLatestBlockDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetBlockDetailsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockDetailsByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetBlockDetailsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetBlockDetailsByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetBlockDetailsByID(ctx, req.(*GetBlockDetailsByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetBlockDetailsByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockDetailsByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetBlockDetailsByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetBlockDetailsByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetBlockDetailsByHeight(ctx, req.(*GetBlockDetailsByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetCollectionByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetCollectionByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetCollectionByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetCollectionByID(ctx, req.(*GetCollectionByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetCollectionByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetCollectionByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetCollectionByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetCollectionByHeight(ctx, req.(*GetCollectionByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetTransactionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetTransactionStatus(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_ExecuteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).ExecuteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/ExecuteScript",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).ExecuteScript(ctx, req.(*ExecuteScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flow.services.observation.ObserveService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveServiceServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ObserveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "flow.services.observation.ObserveService",
	HandlerType: (*ObserveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ObserveService_Ping_Handler,
		},
		{
			MethodName: "GetLatestBlock",
			Handler:    _ObserveService_GetLatestBlock_Handler,
		},
		{
			MethodName: "GetBlockByID",
			Handler:    _ObserveService_GetBlockByID_Handler,
		},
		{
			MethodName: "GetBlockByHeight",
			Handler:    _ObserveService_GetBlockByHeight_Handler,
		},
		{
			MethodName: "GetLatestBlockDetails",
			Handler:    _ObserveService_GetLatestBlockDetails_Handler,
		},
		{
			MethodName: "GetBlockDetailsByID",
			Handler:    _ObserveService_GetBlockDetailsByID_Handler,
		},
		{
			MethodName: "GetBlockDetailsByHeight",
			Handler:    _ObserveService_GetBlockDetailsByHeight_Handler,
		},
		{
			MethodName: "GetCollectionByID",
			Handler:    _ObserveService_GetCollectionByID_Handler,
		},
		{
			MethodName: "GetCollectionByHeight",
			Handler:    _ObserveService_GetCollectionByHeight_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _ObserveService_SendTransaction_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _ObserveService_GetTransaction_Handler,
		},
		{
			MethodName: "GetTransactionStatus",
			Handler:    _ObserveService_GetTransactionStatus_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _ObserveService_GetAccount_Handler,
		},
		{
			MethodName: "ExecuteScript",
			Handler:    _ObserveService_ExecuteScript_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _ObserveService_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/observation/observation.proto",
}
