// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/jordanschalm/lockctx"
	"github.com/onflow/flow-go/model/access"
	"github.com/onflow/flow-go/model/flow"
	"github.com/onflow/flow-go/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewAccountTransactionsBootstrapper creates a new instance of AccountTransactionsBootstrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountTransactionsBootstrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountTransactionsBootstrapper {
	mock := &AccountTransactionsBootstrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AccountTransactionsBootstrapper is an autogenerated mock type for the AccountTransactionsBootstrapper type
type AccountTransactionsBootstrapper struct {
	mock.Mock
}

type AccountTransactionsBootstrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountTransactionsBootstrapper) EXPECT() *AccountTransactionsBootstrapper_Expecter {
	return &AccountTransactionsBootstrapper_Expecter{mock: &_m.Mock}
}

// ByAddress provides a mock function for the type AccountTransactionsBootstrapper
func (_mock *AccountTransactionsBootstrapper) ByAddress(account flow.Address, cursor *access.AccountTransactionCursor) (storage.AccountTransactionIterator, error) {
	ret := _mock.Called(account, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ByAddress")
	}

	var r0 storage.AccountTransactionIterator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(flow.Address, *access.AccountTransactionCursor) (storage.AccountTransactionIterator, error)); ok {
		return returnFunc(account, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(flow.Address, *access.AccountTransactionCursor) storage.AccountTransactionIterator); ok {
		r0 = returnFunc(account, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.AccountTransactionIterator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(flow.Address, *access.AccountTransactionCursor) error); ok {
		r1 = returnFunc(account, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountTransactionsBootstrapper_ByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ByAddress'
type AccountTransactionsBootstrapper_ByAddress_Call struct {
	*mock.Call
}

// ByAddress is a helper method to define mock.On call
//   - account flow.Address
//   - cursor *access.AccountTransactionCursor
func (_e *AccountTransactionsBootstrapper_Expecter) ByAddress(account interface{}, cursor interface{}) *AccountTransactionsBootstrapper_ByAddress_Call {
	return &AccountTransactionsBootstrapper_ByAddress_Call{Call: _e.mock.On("ByAddress", account, cursor)}
}

func (_c *AccountTransactionsBootstrapper_ByAddress_Call) Run(run func(account flow.Address, cursor *access.AccountTransactionCursor)) *AccountTransactionsBootstrapper_ByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Address
		if args[0] != nil {
			arg0 = args[0].(flow.Address)
		}
		var arg1 *access.AccountTransactionCursor
		if args[1] != nil {
			arg1 = args[1].(*access.AccountTransactionCursor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AccountTransactionsBootstrapper_ByAddress_Call) Return(v storage.AccountTransactionIterator, err error) *AccountTransactionsBootstrapper_ByAddress_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AccountTransactionsBootstrapper_ByAddress_Call) RunAndReturn(run func(account flow.Address, cursor *access.AccountTransactionCursor) (storage.AccountTransactionIterator, error)) *AccountTransactionsBootstrapper_ByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// FirstIndexedHeight provides a mock function for the type AccountTransactionsBootstrapper
func (_mock *AccountTransactionsBootstrapper) FirstIndexedHeight() (uint64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FirstIndexedHeight")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uint64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountTransactionsBootstrapper_FirstIndexedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstIndexedHeight'
type AccountTransactionsBootstrapper_FirstIndexedHeight_Call struct {
	*mock.Call
}

// FirstIndexedHeight is a helper method to define mock.On call
func (_e *AccountTransactionsBootstrapper_Expecter) FirstIndexedHeight() *AccountTransactionsBootstrapper_FirstIndexedHeight_Call {
	return &AccountTransactionsBootstrapper_FirstIndexedHeight_Call{Call: _e.mock.On("FirstIndexedHeight")}
}

func (_c *AccountTransactionsBootstrapper_FirstIndexedHeight_Call) Run(run func()) *AccountTransactionsBootstrapper_FirstIndexedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AccountTransactionsBootstrapper_FirstIndexedHeight_Call) Return(v uint64, err error) *AccountTransactionsBootstrapper_FirstIndexedHeight_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AccountTransactionsBootstrapper_FirstIndexedHeight_Call) RunAndReturn(run func() (uint64, error)) *AccountTransactionsBootstrapper_FirstIndexedHeight_Call {
	_c.Call.Return(run)
	return _c
}

// LatestIndexedHeight provides a mock function for the type AccountTransactionsBootstrapper
func (_mock *AccountTransactionsBootstrapper) LatestIndexedHeight() (uint64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LatestIndexedHeight")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uint64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AccountTransactionsBootstrapper_LatestIndexedHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestIndexedHeight'
type AccountTransactionsBootstrapper_LatestIndexedHeight_Call struct {
	*mock.Call
}

// LatestIndexedHeight is a helper method to define mock.On call
func (_e *AccountTransactionsBootstrapper_Expecter) LatestIndexedHeight() *AccountTransactionsBootstrapper_LatestIndexedHeight_Call {
	return &AccountTransactionsBootstrapper_LatestIndexedHeight_Call{Call: _e.mock.On("LatestIndexedHeight")}
}

func (_c *AccountTransactionsBootstrapper_LatestIndexedHeight_Call) Run(run func()) *AccountTransactionsBootstrapper_LatestIndexedHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AccountTransactionsBootstrapper_LatestIndexedHeight_Call) Return(v uint64, err error) *AccountTransactionsBootstrapper_LatestIndexedHeight_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *AccountTransactionsBootstrapper_LatestIndexedHeight_Call) RunAndReturn(run func() (uint64, error)) *AccountTransactionsBootstrapper_LatestIndexedHeight_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type AccountTransactionsBootstrapper
func (_mock *AccountTransactionsBootstrapper) Store(lctx lockctx.Proof, rw storage.ReaderBatchWriter, blockHeight uint64, txData []access.AccountTransaction) error {
	ret := _mock.Called(lctx, rw, blockHeight, txData)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(lockctx.Proof, storage.ReaderBatchWriter, uint64, []access.AccountTransaction) error); ok {
		r0 = returnFunc(lctx, rw, blockHeight, txData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AccountTransactionsBootstrapper_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type AccountTransactionsBootstrapper_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - lctx lockctx.Proof
//   - rw storage.ReaderBatchWriter
//   - blockHeight uint64
//   - txData []access.AccountTransaction
func (_e *AccountTransactionsBootstrapper_Expecter) Store(lctx interface{}, rw interface{}, blockHeight interface{}, txData interface{}) *AccountTransactionsBootstrapper_Store_Call {
	return &AccountTransactionsBootstrapper_Store_Call{Call: _e.mock.On("Store", lctx, rw, blockHeight, txData)}
}

func (_c *AccountTransactionsBootstrapper_Store_Call) Run(run func(lctx lockctx.Proof, rw storage.ReaderBatchWriter, blockHeight uint64, txData []access.AccountTransaction)) *AccountTransactionsBootstrapper_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lockctx.Proof
		if args[0] != nil {
			arg0 = args[0].(lockctx.Proof)
		}
		var arg1 storage.ReaderBatchWriter
		if args[1] != nil {
			arg1 = args[1].(storage.ReaderBatchWriter)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		var arg3 []access.AccountTransaction
		if args[3] != nil {
			arg3 = args[3].([]access.AccountTransaction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AccountTransactionsBootstrapper_Store_Call) Return(err error) *AccountTransactionsBootstrapper_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AccountTransactionsBootstrapper_Store_Call) RunAndReturn(run func(lctx lockctx.Proof, rw storage.ReaderBatchWriter, blockHeight uint64, txData []access.AccountTransaction) error) *AccountTransactionsBootstrapper_Store_Call {
	_c.Call.Return(run)
	return _c
}

// UninitializedFirstHeight provides a mock function for the type AccountTransactionsBootstrapper
func (_mock *AccountTransactionsBootstrapper) UninitializedFirstHeight() (uint64, bool) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UninitializedFirstHeight")
	}

	var r0 uint64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func() (uint64, bool)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func() bool); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// AccountTransactionsBootstrapper_UninitializedFirstHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UninitializedFirstHeight'
type AccountTransactionsBootstrapper_UninitializedFirstHeight_Call struct {
	*mock.Call
}

// UninitializedFirstHeight is a helper method to define mock.On call
func (_e *AccountTransactionsBootstrapper_Expecter) UninitializedFirstHeight() *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call {
	return &AccountTransactionsBootstrapper_UninitializedFirstHeight_Call{Call: _e.mock.On("UninitializedFirstHeight")}
}

func (_c *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call) Run(run func()) *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call) Return(v uint64, b bool) *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call) RunAndReturn(run func() (uint64, bool)) *AccountTransactionsBootstrapper_UninitializedFirstHeight_Call {
	_c.Call.Return(run)
	return _c
}
