// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import flow "github.com/dapperlabs/flow-go/model/flow"
import mock "github.com/stretchr/testify/mock"

// Collections is an autogenerated mock type for the Collections type
type Collections struct {
	mock.Mock
}

// ByFingerprint provides a mock function with given fields: hash
func (_m *Collections) ByFingerprint(hash flow.Fingerprint) (*flow.Collection, error) {
	ret := _m.Called(hash)

	var r0 *flow.Collection
	if rf, ok := ret.Get(0).(func(flow.Fingerprint) *flow.Collection); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flow.Collection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(flow.Fingerprint) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GuaranteeByFingerprint provides a mock function with given fields: hash
func (_m *Collections) GuaranteeByFingerprint(hash flow.Fingerprint) (*flow.CollectionGuarantee, error) {
	ret := _m.Called(hash)

	var r0 *flow.CollectionGuarantee
	if rf, ok := ret.Get(0).(func(flow.Fingerprint) *flow.CollectionGuarantee); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flow.CollectionGuarantee)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(flow.Fingerprint) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertGuarantee provides a mock function with given fields: gc
func (_m *Collections) InsertGuarantee(gc *flow.CollectionGuarantee) error {
	ret := _m.Called(gc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*flow.CollectionGuarantee) error); ok {
		r0 = rf(gc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Remove provides a mock function with given fields: hash
func (_m *Collections) Remove(hash flow.Fingerprint) error {
	ret := _m.Called(hash)

	var r0 error
	if rf, ok := ret.Get(0).(func(flow.Fingerprint) error); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: collection
func (_m *Collections) Save(collection *flow.Collection) error {
	ret := _m.Called(collection)

	var r0 error
	if rf, ok := ret.Get(0).(func(*flow.Collection) error); ok {
		r0 = rf(collection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionsByFingerprint provides a mock function with given fields: hash
func (_m *Collections) TransactionsByFingerprint(hash flow.Fingerprint) ([]*flow.Transaction, error) {
	ret := _m.Called(hash)

	var r0 []*flow.Transaction
	if rf, ok := ret.Get(0).(func(flow.Fingerprint) []*flow.Transaction); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*flow.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(flow.Fingerprint) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
