// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	crypto "github.com/dapperlabs/flow-go/crypto"
	flow "github.com/dapperlabs/flow-go/model/flow"

	mock "github.com/stretchr/testify/mock"
)

// Headers is an autogenerated mock type for the Headers type
type Headers struct {
	mock.Mock
}

// ByHash provides a mock function with given fields: hash
func (_m *Headers) ByHash(hash crypto.Hash) (*flow.Header, error) {
	ret := _m.Called(hash)

	var r0 *flow.Header
	if rf, ok := ret.Get(0).(func(crypto.Hash) *flow.Header); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flow.Header)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(crypto.Hash) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ByNumber provides a mock function with given fields: number
func (_m *Headers) ByNumber(number uint64) (*flow.Header, error) {
	ret := _m.Called(number)

	var r0 *flow.Header
	if rf, ok := ret.Get(0).(func(uint64) *flow.Header); ok {
		r0 = rf(number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flow.Header)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
