// Code generated by mockery. DO NOT EDIT.

package mock

import (
	flow "github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// NodeDisallowList is an autogenerated mock type for the NodeDisallowList type
type NodeDisallowList struct {
	mock.Mock
}

// Retrieve provides a mock function with given fields: disallowList
func (_m *NodeDisallowList) Retrieve(disallowList *map[flow.Identifier]struct{}) error {
	ret := _m.Called(disallowList)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*map[flow.Identifier]struct{}) error); ok {
		r0 = rf(disallowList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: disallowList
func (_m *NodeDisallowList) Store(disallowList map[flow.Identifier]struct{}) error {
	ret := _m.Called(disallowList)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[flow.Identifier]struct{}) error); ok {
		r0 = rf(disallowList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNodeDisallowList creates a new instance of NodeDisallowList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeDisallowList(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeDisallowList {
	mock := &NodeDisallowList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
