// Code generated by mockery v2.21.4. DO NOT EDIT.

package mock

import (
	flow "github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// ClusterEvents is an autogenerated mock type for the ClusterEvents type
type ClusterEvents struct {
	mock.Mock
}

// ActiveClustersChanged provides a mock function with given fields: _a0
func (_m *ClusterEvents) ActiveClustersChanged(_a0 flow.ChainIDList) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewClusterEvents interface {
	mock.TestingT
	Cleanup(func())
}

// NewClusterEvents creates a new instance of ClusterEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClusterEvents(t mockConstructorTestingTNewClusterEvents) *ClusterEvents {
	mock := &ClusterEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
