// Code generated by mockery v2.13.0. DO NOT EDIT.

package mocktracker

import mock "github.com/stretchr/testify/mock"

// StorageOption is an autogenerated mock type for the StorageOption type
type StorageOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *StorageOption) Execute(_a0 *tracker.storage) {
	_m.Called(_a0)
}

type NewStorageOptionT interface {
	mock.TestingT
	Cleanup(func())
}

// NewStorageOption creates a new instance of StorageOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStorageOption(t NewStorageOptionT) *StorageOption {
	mock := &StorageOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
