// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/onflow/flow-go/consensus/hotstuff"
	"github.com/onflow/flow-go/consensus/hotstuff/model"
	"github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// OnBlockIncorporated provides a mock function for the type Consumer
func (_mock *Consumer) OnBlockIncorporated(block *model.Block) {
	_mock.Called(block)
	return
}

// Consumer_OnBlockIncorporated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnBlockIncorporated'
type Consumer_OnBlockIncorporated_Call struct {
	*mock.Call
}

// OnBlockIncorporated is a helper method to define mock.On call
//   - block *model.Block
func (_e *Consumer_Expecter) OnBlockIncorporated(block interface{}) *Consumer_OnBlockIncorporated_Call {
	return &Consumer_OnBlockIncorporated_Call{Call: _e.mock.On("OnBlockIncorporated", block)}
}

func (_c *Consumer_OnBlockIncorporated_Call) Run(run func(block *model.Block)) *Consumer_OnBlockIncorporated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Block
		if args[0] != nil {
			arg0 = args[0].(*model.Block)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnBlockIncorporated_Call) Return() *Consumer_OnBlockIncorporated_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnBlockIncorporated_Call) RunAndReturn(run func(block *model.Block)) *Consumer_OnBlockIncorporated_Call {
	_c.Run(run)
	return _c
}

// OnCurrentViewDetails provides a mock function for the type Consumer
func (_mock *Consumer) OnCurrentViewDetails(currentView uint64, finalizedView uint64, currentLeader flow.Identifier) {
	_mock.Called(currentView, finalizedView, currentLeader)
	return
}

// Consumer_OnCurrentViewDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnCurrentViewDetails'
type Consumer_OnCurrentViewDetails_Call struct {
	*mock.Call
}

// OnCurrentViewDetails is a helper method to define mock.On call
//   - currentView uint64
//   - finalizedView uint64
//   - currentLeader flow.Identifier
func (_e *Consumer_Expecter) OnCurrentViewDetails(currentView interface{}, finalizedView interface{}, currentLeader interface{}) *Consumer_OnCurrentViewDetails_Call {
	return &Consumer_OnCurrentViewDetails_Call{Call: _e.mock.On("OnCurrentViewDetails", currentView, finalizedView, currentLeader)}
}

func (_c *Consumer_OnCurrentViewDetails_Call) Run(run func(currentView uint64, finalizedView uint64, currentLeader flow.Identifier)) *Consumer_OnCurrentViewDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 flow.Identifier
		if args[2] != nil {
			arg2 = args[2].(flow.Identifier)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Consumer_OnCurrentViewDetails_Call) Return() *Consumer_OnCurrentViewDetails_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnCurrentViewDetails_Call) RunAndReturn(run func(currentView uint64, finalizedView uint64, currentLeader flow.Identifier)) *Consumer_OnCurrentViewDetails_Call {
	_c.Run(run)
	return _c
}

// OnDoubleProposeDetected provides a mock function for the type Consumer
func (_mock *Consumer) OnDoubleProposeDetected(block *model.Block, block1 *model.Block) {
	_mock.Called(block, block1)
	return
}

// Consumer_OnDoubleProposeDetected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnDoubleProposeDetected'
type Consumer_OnDoubleProposeDetected_Call struct {
	*mock.Call
}

// OnDoubleProposeDetected is a helper method to define mock.On call
//   - block *model.Block
//   - block1 *model.Block
func (_e *Consumer_Expecter) OnDoubleProposeDetected(block interface{}, block1 interface{}) *Consumer_OnDoubleProposeDetected_Call {
	return &Consumer_OnDoubleProposeDetected_Call{Call: _e.mock.On("OnDoubleProposeDetected", block, block1)}
}

func (_c *Consumer_OnDoubleProposeDetected_Call) Run(run func(block *model.Block, block1 *model.Block)) *Consumer_OnDoubleProposeDetected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Block
		if args[0] != nil {
			arg0 = args[0].(*model.Block)
		}
		var arg1 *model.Block
		if args[1] != nil {
			arg1 = args[1].(*model.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnDoubleProposeDetected_Call) Return() *Consumer_OnDoubleProposeDetected_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnDoubleProposeDetected_Call) RunAndReturn(run func(block *model.Block, block1 *model.Block)) *Consumer_OnDoubleProposeDetected_Call {
	_c.Run(run)
	return _c
}

// OnEventProcessed provides a mock function for the type Consumer
func (_mock *Consumer) OnEventProcessed() {
	_mock.Called()
	return
}

// Consumer_OnEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnEventProcessed'
type Consumer_OnEventProcessed_Call struct {
	*mock.Call
}

// OnEventProcessed is a helper method to define mock.On call
func (_e *Consumer_Expecter) OnEventProcessed() *Consumer_OnEventProcessed_Call {
	return &Consumer_OnEventProcessed_Call{Call: _e.mock.On("OnEventProcessed")}
}

func (_c *Consumer_OnEventProcessed_Call) Run(run func()) *Consumer_OnEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Consumer_OnEventProcessed_Call) Return() *Consumer_OnEventProcessed_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnEventProcessed_Call) RunAndReturn(run func()) *Consumer_OnEventProcessed_Call {
	_c.Run(run)
	return _c
}

// OnFinalizedBlock provides a mock function for the type Consumer
func (_mock *Consumer) OnFinalizedBlock(block *model.Block) {
	_mock.Called(block)
	return
}

// Consumer_OnFinalizedBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFinalizedBlock'
type Consumer_OnFinalizedBlock_Call struct {
	*mock.Call
}

// OnFinalizedBlock is a helper method to define mock.On call
//   - block *model.Block
func (_e *Consumer_Expecter) OnFinalizedBlock(block interface{}) *Consumer_OnFinalizedBlock_Call {
	return &Consumer_OnFinalizedBlock_Call{Call: _e.mock.On("OnFinalizedBlock", block)}
}

func (_c *Consumer_OnFinalizedBlock_Call) Run(run func(block *model.Block)) *Consumer_OnFinalizedBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Block
		if args[0] != nil {
			arg0 = args[0].(*model.Block)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnFinalizedBlock_Call) Return() *Consumer_OnFinalizedBlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnFinalizedBlock_Call) RunAndReturn(run func(block *model.Block)) *Consumer_OnFinalizedBlock_Call {
	_c.Run(run)
	return _c
}

// OnInvalidBlockDetected provides a mock function for the type Consumer
func (_mock *Consumer) OnInvalidBlockDetected(err flow.Slashable[model.InvalidProposalError]) {
	_mock.Called(err)
	return
}

// Consumer_OnInvalidBlockDetected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnInvalidBlockDetected'
type Consumer_OnInvalidBlockDetected_Call struct {
	*mock.Call
}

// OnInvalidBlockDetected is a helper method to define mock.On call
//   - err flow.Slashable[model.InvalidProposalError]
func (_e *Consumer_Expecter) OnInvalidBlockDetected(err interface{}) *Consumer_OnInvalidBlockDetected_Call {
	return &Consumer_OnInvalidBlockDetected_Call{Call: _e.mock.On("OnInvalidBlockDetected", err)}
}

func (_c *Consumer_OnInvalidBlockDetected_Call) Run(run func(err flow.Slashable[model.InvalidProposalError])) *Consumer_OnInvalidBlockDetected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 flow.Slashable[model.InvalidProposalError]
		if args[0] != nil {
			arg0 = args[0].(flow.Slashable[model.InvalidProposalError])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnInvalidBlockDetected_Call) Return() *Consumer_OnInvalidBlockDetected_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnInvalidBlockDetected_Call) RunAndReturn(run func(err flow.Slashable[model.InvalidProposalError])) *Consumer_OnInvalidBlockDetected_Call {
	_c.Run(run)
	return _c
}

// OnLocalTimeout provides a mock function for the type Consumer
func (_mock *Consumer) OnLocalTimeout(currentView uint64) {
	_mock.Called(currentView)
	return
}

// Consumer_OnLocalTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnLocalTimeout'
type Consumer_OnLocalTimeout_Call struct {
	*mock.Call
}

// OnLocalTimeout is a helper method to define mock.On call
//   - currentView uint64
func (_e *Consumer_Expecter) OnLocalTimeout(currentView interface{}) *Consumer_OnLocalTimeout_Call {
	return &Consumer_OnLocalTimeout_Call{Call: _e.mock.On("OnLocalTimeout", currentView)}
}

func (_c *Consumer_OnLocalTimeout_Call) Run(run func(currentView uint64)) *Consumer_OnLocalTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnLocalTimeout_Call) Return() *Consumer_OnLocalTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnLocalTimeout_Call) RunAndReturn(run func(currentView uint64)) *Consumer_OnLocalTimeout_Call {
	_c.Run(run)
	return _c
}

// OnOwnProposal provides a mock function for the type Consumer
func (_mock *Consumer) OnOwnProposal(proposal *flow.ProposalHeader, targetPublicationTime time.Time) {
	_mock.Called(proposal, targetPublicationTime)
	return
}

// Consumer_OnOwnProposal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnOwnProposal'
type Consumer_OnOwnProposal_Call struct {
	*mock.Call
}

// OnOwnProposal is a helper method to define mock.On call
//   - proposal *flow.ProposalHeader
//   - targetPublicationTime time.Time
func (_e *Consumer_Expecter) OnOwnProposal(proposal interface{}, targetPublicationTime interface{}) *Consumer_OnOwnProposal_Call {
	return &Consumer_OnOwnProposal_Call{Call: _e.mock.On("OnOwnProposal", proposal, targetPublicationTime)}
}

func (_c *Consumer_OnOwnProposal_Call) Run(run func(proposal *flow.ProposalHeader, targetPublicationTime time.Time)) *Consumer_OnOwnProposal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *flow.ProposalHeader
		if args[0] != nil {
			arg0 = args[0].(*flow.ProposalHeader)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnOwnProposal_Call) Return() *Consumer_OnOwnProposal_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnOwnProposal_Call) RunAndReturn(run func(proposal *flow.ProposalHeader, targetPublicationTime time.Time)) *Consumer_OnOwnProposal_Call {
	_c.Run(run)
	return _c
}

// OnOwnTimeout provides a mock function for the type Consumer
func (_mock *Consumer) OnOwnTimeout(timeout *model.TimeoutObject) {
	_mock.Called(timeout)
	return
}

// Consumer_OnOwnTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnOwnTimeout'
type Consumer_OnOwnTimeout_Call struct {
	*mock.Call
}

// OnOwnTimeout is a helper method to define mock.On call
//   - timeout *model.TimeoutObject
func (_e *Consumer_Expecter) OnOwnTimeout(timeout interface{}) *Consumer_OnOwnTimeout_Call {
	return &Consumer_OnOwnTimeout_Call{Call: _e.mock.On("OnOwnTimeout", timeout)}
}

func (_c *Consumer_OnOwnTimeout_Call) Run(run func(timeout *model.TimeoutObject)) *Consumer_OnOwnTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.TimeoutObject
		if args[0] != nil {
			arg0 = args[0].(*model.TimeoutObject)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnOwnTimeout_Call) Return() *Consumer_OnOwnTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnOwnTimeout_Call) RunAndReturn(run func(timeout *model.TimeoutObject)) *Consumer_OnOwnTimeout_Call {
	_c.Run(run)
	return _c
}

// OnOwnVote provides a mock function for the type Consumer
func (_mock *Consumer) OnOwnVote(vote *model.Vote, recipientID flow.Identifier) {
	_mock.Called(vote, recipientID)
	return
}

// Consumer_OnOwnVote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnOwnVote'
type Consumer_OnOwnVote_Call struct {
	*mock.Call
}

// OnOwnVote is a helper method to define mock.On call
//   - vote *model.Vote
//   - recipientID flow.Identifier
func (_e *Consumer_Expecter) OnOwnVote(vote interface{}, recipientID interface{}) *Consumer_OnOwnVote_Call {
	return &Consumer_OnOwnVote_Call{Call: _e.mock.On("OnOwnVote", vote, recipientID)}
}

func (_c *Consumer_OnOwnVote_Call) Run(run func(vote *model.Vote, recipientID flow.Identifier)) *Consumer_OnOwnVote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Vote
		if args[0] != nil {
			arg0 = args[0].(*model.Vote)
		}
		var arg1 flow.Identifier
		if args[1] != nil {
			arg1 = args[1].(flow.Identifier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnOwnVote_Call) Return() *Consumer_OnOwnVote_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnOwnVote_Call) RunAndReturn(run func(vote *model.Vote, recipientID flow.Identifier)) *Consumer_OnOwnVote_Call {
	_c.Run(run)
	return _c
}

// OnPartialTc provides a mock function for the type Consumer
func (_mock *Consumer) OnPartialTc(currentView uint64, partialTc *hotstuff.PartialTcCreated) {
	_mock.Called(currentView, partialTc)
	return
}

// Consumer_OnPartialTc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnPartialTc'
type Consumer_OnPartialTc_Call struct {
	*mock.Call
}

// OnPartialTc is a helper method to define mock.On call
//   - currentView uint64
//   - partialTc *hotstuff.PartialTcCreated
func (_e *Consumer_Expecter) OnPartialTc(currentView interface{}, partialTc interface{}) *Consumer_OnPartialTc_Call {
	return &Consumer_OnPartialTc_Call{Call: _e.mock.On("OnPartialTc", currentView, partialTc)}
}

func (_c *Consumer_OnPartialTc_Call) Run(run func(currentView uint64, partialTc *hotstuff.PartialTcCreated)) *Consumer_OnPartialTc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *hotstuff.PartialTcCreated
		if args[1] != nil {
			arg1 = args[1].(*hotstuff.PartialTcCreated)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnPartialTc_Call) Return() *Consumer_OnPartialTc_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnPartialTc_Call) RunAndReturn(run func(currentView uint64, partialTc *hotstuff.PartialTcCreated)) *Consumer_OnPartialTc_Call {
	_c.Run(run)
	return _c
}

// OnQcTriggeredViewChange provides a mock function for the type Consumer
func (_mock *Consumer) OnQcTriggeredViewChange(oldView uint64, newView uint64, qc *flow.QuorumCertificate) {
	_mock.Called(oldView, newView, qc)
	return
}

// Consumer_OnQcTriggeredViewChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnQcTriggeredViewChange'
type Consumer_OnQcTriggeredViewChange_Call struct {
	*mock.Call
}

// OnQcTriggeredViewChange is a helper method to define mock.On call
//   - oldView uint64
//   - newView uint64
//   - qc *flow.QuorumCertificate
func (_e *Consumer_Expecter) OnQcTriggeredViewChange(oldView interface{}, newView interface{}, qc interface{}) *Consumer_OnQcTriggeredViewChange_Call {
	return &Consumer_OnQcTriggeredViewChange_Call{Call: _e.mock.On("OnQcTriggeredViewChange", oldView, newView, qc)}
}

func (_c *Consumer_OnQcTriggeredViewChange_Call) Run(run func(oldView uint64, newView uint64, qc *flow.QuorumCertificate)) *Consumer_OnQcTriggeredViewChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *flow.QuorumCertificate
		if args[2] != nil {
			arg2 = args[2].(*flow.QuorumCertificate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Consumer_OnQcTriggeredViewChange_Call) Return() *Consumer_OnQcTriggeredViewChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnQcTriggeredViewChange_Call) RunAndReturn(run func(oldView uint64, newView uint64, qc *flow.QuorumCertificate)) *Consumer_OnQcTriggeredViewChange_Call {
	_c.Run(run)
	return _c
}

// OnReceiveProposal provides a mock function for the type Consumer
func (_mock *Consumer) OnReceiveProposal(currentView uint64, proposal *model.SignedProposal) {
	_mock.Called(currentView, proposal)
	return
}

// Consumer_OnReceiveProposal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnReceiveProposal'
type Consumer_OnReceiveProposal_Call struct {
	*mock.Call
}

// OnReceiveProposal is a helper method to define mock.On call
//   - currentView uint64
//   - proposal *model.SignedProposal
func (_e *Consumer_Expecter) OnReceiveProposal(currentView interface{}, proposal interface{}) *Consumer_OnReceiveProposal_Call {
	return &Consumer_OnReceiveProposal_Call{Call: _e.mock.On("OnReceiveProposal", currentView, proposal)}
}

func (_c *Consumer_OnReceiveProposal_Call) Run(run func(currentView uint64, proposal *model.SignedProposal)) *Consumer_OnReceiveProposal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *model.SignedProposal
		if args[1] != nil {
			arg1 = args[1].(*model.SignedProposal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnReceiveProposal_Call) Return() *Consumer_OnReceiveProposal_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnReceiveProposal_Call) RunAndReturn(run func(currentView uint64, proposal *model.SignedProposal)) *Consumer_OnReceiveProposal_Call {
	_c.Run(run)
	return _c
}

// OnReceiveQc provides a mock function for the type Consumer
func (_mock *Consumer) OnReceiveQc(currentView uint64, qc *flow.QuorumCertificate) {
	_mock.Called(currentView, qc)
	return
}

// Consumer_OnReceiveQc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnReceiveQc'
type Consumer_OnReceiveQc_Call struct {
	*mock.Call
}

// OnReceiveQc is a helper method to define mock.On call
//   - currentView uint64
//   - qc *flow.QuorumCertificate
func (_e *Consumer_Expecter) OnReceiveQc(currentView interface{}, qc interface{}) *Consumer_OnReceiveQc_Call {
	return &Consumer_OnReceiveQc_Call{Call: _e.mock.On("OnReceiveQc", currentView, qc)}
}

func (_c *Consumer_OnReceiveQc_Call) Run(run func(currentView uint64, qc *flow.QuorumCertificate)) *Consumer_OnReceiveQc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *flow.QuorumCertificate
		if args[1] != nil {
			arg1 = args[1].(*flow.QuorumCertificate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnReceiveQc_Call) Return() *Consumer_OnReceiveQc_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnReceiveQc_Call) RunAndReturn(run func(currentView uint64, qc *flow.QuorumCertificate)) *Consumer_OnReceiveQc_Call {
	_c.Run(run)
	return _c
}

// OnReceiveTc provides a mock function for the type Consumer
func (_mock *Consumer) OnReceiveTc(currentView uint64, tc *flow.TimeoutCertificate) {
	_mock.Called(currentView, tc)
	return
}

// Consumer_OnReceiveTc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnReceiveTc'
type Consumer_OnReceiveTc_Call struct {
	*mock.Call
}

// OnReceiveTc is a helper method to define mock.On call
//   - currentView uint64
//   - tc *flow.TimeoutCertificate
func (_e *Consumer_Expecter) OnReceiveTc(currentView interface{}, tc interface{}) *Consumer_OnReceiveTc_Call {
	return &Consumer_OnReceiveTc_Call{Call: _e.mock.On("OnReceiveTc", currentView, tc)}
}

func (_c *Consumer_OnReceiveTc_Call) Run(run func(currentView uint64, tc *flow.TimeoutCertificate)) *Consumer_OnReceiveTc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 *flow.TimeoutCertificate
		if args[1] != nil {
			arg1 = args[1].(*flow.TimeoutCertificate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnReceiveTc_Call) Return() *Consumer_OnReceiveTc_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnReceiveTc_Call) RunAndReturn(run func(currentView uint64, tc *flow.TimeoutCertificate)) *Consumer_OnReceiveTc_Call {
	_c.Run(run)
	return _c
}

// OnStart provides a mock function for the type Consumer
func (_mock *Consumer) OnStart(currentView uint64) {
	_mock.Called(currentView)
	return
}

// Consumer_OnStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStart'
type Consumer_OnStart_Call struct {
	*mock.Call
}

// OnStart is a helper method to define mock.On call
//   - currentView uint64
func (_e *Consumer_Expecter) OnStart(currentView interface{}) *Consumer_OnStart_Call {
	return &Consumer_OnStart_Call{Call: _e.mock.On("OnStart", currentView)}
}

func (_c *Consumer_OnStart_Call) Run(run func(currentView uint64)) *Consumer_OnStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnStart_Call) Return() *Consumer_OnStart_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnStart_Call) RunAndReturn(run func(currentView uint64)) *Consumer_OnStart_Call {
	_c.Run(run)
	return _c
}

// OnStartingTimeout provides a mock function for the type Consumer
func (_mock *Consumer) OnStartingTimeout(timerInfo model.TimerInfo) {
	_mock.Called(timerInfo)
	return
}

// Consumer_OnStartingTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnStartingTimeout'
type Consumer_OnStartingTimeout_Call struct {
	*mock.Call
}

// OnStartingTimeout is a helper method to define mock.On call
//   - timerInfo model.TimerInfo
func (_e *Consumer_Expecter) OnStartingTimeout(timerInfo interface{}) *Consumer_OnStartingTimeout_Call {
	return &Consumer_OnStartingTimeout_Call{Call: _e.mock.On("OnStartingTimeout", timerInfo)}
}

func (_c *Consumer_OnStartingTimeout_Call) Run(run func(timerInfo model.TimerInfo)) *Consumer_OnStartingTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.TimerInfo
		if args[0] != nil {
			arg0 = args[0].(model.TimerInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_OnStartingTimeout_Call) Return() *Consumer_OnStartingTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnStartingTimeout_Call) RunAndReturn(run func(timerInfo model.TimerInfo)) *Consumer_OnStartingTimeout_Call {
	_c.Run(run)
	return _c
}

// OnTcTriggeredViewChange provides a mock function for the type Consumer
func (_mock *Consumer) OnTcTriggeredViewChange(oldView uint64, newView uint64, tc *flow.TimeoutCertificate) {
	_mock.Called(oldView, newView, tc)
	return
}

// Consumer_OnTcTriggeredViewChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnTcTriggeredViewChange'
type Consumer_OnTcTriggeredViewChange_Call struct {
	*mock.Call
}

// OnTcTriggeredViewChange is a helper method to define mock.On call
//   - oldView uint64
//   - newView uint64
//   - tc *flow.TimeoutCertificate
func (_e *Consumer_Expecter) OnTcTriggeredViewChange(oldView interface{}, newView interface{}, tc interface{}) *Consumer_OnTcTriggeredViewChange_Call {
	return &Consumer_OnTcTriggeredViewChange_Call{Call: _e.mock.On("OnTcTriggeredViewChange", oldView, newView, tc)}
}

func (_c *Consumer_OnTcTriggeredViewChange_Call) Run(run func(oldView uint64, newView uint64, tc *flow.TimeoutCertificate)) *Consumer_OnTcTriggeredViewChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 *flow.TimeoutCertificate
		if args[2] != nil {
			arg2 = args[2].(*flow.TimeoutCertificate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Consumer_OnTcTriggeredViewChange_Call) Return() *Consumer_OnTcTriggeredViewChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnTcTriggeredViewChange_Call) RunAndReturn(run func(oldView uint64, newView uint64, tc *flow.TimeoutCertificate)) *Consumer_OnTcTriggeredViewChange_Call {
	_c.Run(run)
	return _c
}

// OnViewChange provides a mock function for the type Consumer
func (_mock *Consumer) OnViewChange(oldView uint64, newView uint64) {
	_mock.Called(oldView, newView)
	return
}

// Consumer_OnViewChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnViewChange'
type Consumer_OnViewChange_Call struct {
	*mock.Call
}

// OnViewChange is a helper method to define mock.On call
//   - oldView uint64
//   - newView uint64
func (_e *Consumer_Expecter) OnViewChange(oldView interface{}, newView interface{}) *Consumer_OnViewChange_Call {
	return &Consumer_OnViewChange_Call{Call: _e.mock.On("OnViewChange", oldView, newView)}
}

func (_c *Consumer_OnViewChange_Call) Run(run func(oldView uint64, newView uint64)) *Consumer_OnViewChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_OnViewChange_Call) Return() *Consumer_OnViewChange_Call {
	_c.Call.Return()
	return _c
}

func (_c *Consumer_OnViewChange_Call) RunAndReturn(run func(oldView uint64, newView uint64)) *Consumer_OnViewChange_Call {
	_c.Run(run)
	return _c
}
