// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/dapperlabs/flow-go/consensus/hotstuff/model"

// Voter is an autogenerated mock type for the Voter type
type Voter struct {
	mock.Mock
}

// ProduceVoteIfVotable provides a mock function with given fields: block, curView
func (_m *Voter) ProduceVoteIfVotable(block *model.Block, curView uint64) (*model.Vote, error) {
	ret := _m.Called(block, curView)

	var r0 *model.Vote
	if rf, ok := ret.Get(0).(func(*model.Block, uint64) *model.Vote); ok {
		r0 = rf(block, curView)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vote)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Block, uint64) error); ok {
		r1 = rf(block, curView)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
