// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// NewCollectionExecutedMetric creates a new instance of CollectionExecutedMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollectionExecutedMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollectionExecutedMetric {
	mock := &CollectionExecutedMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CollectionExecutedMetric is an autogenerated mock type for the CollectionExecutedMetric type
type CollectionExecutedMetric struct {
	mock.Mock
}

type CollectionExecutedMetric_Expecter struct {
	mock *mock.Mock
}

func (_m *CollectionExecutedMetric) EXPECT() *CollectionExecutedMetric_Expecter {
	return &CollectionExecutedMetric_Expecter{mock: &_m.Mock}
}

// BlockFinalized provides a mock function for the type CollectionExecutedMetric
func (_mock *CollectionExecutedMetric) BlockFinalized(block *flow.Block) {
	_mock.Called(block)
	return
}

// CollectionExecutedMetric_BlockFinalized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockFinalized'
type CollectionExecutedMetric_BlockFinalized_Call struct {
	*mock.Call
}

// BlockFinalized is a helper method to define mock.On call
//   - block *flow.Block
func (_e *CollectionExecutedMetric_Expecter) BlockFinalized(block interface{}) *CollectionExecutedMetric_BlockFinalized_Call {
	return &CollectionExecutedMetric_BlockFinalized_Call{Call: _e.mock.On("BlockFinalized", block)}
}

func (_c *CollectionExecutedMetric_BlockFinalized_Call) Run(run func(block *flow.Block)) *CollectionExecutedMetric_BlockFinalized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *flow.Block
		if args[0] != nil {
			arg0 = args[0].(*flow.Block)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CollectionExecutedMetric_BlockFinalized_Call) Return() *CollectionExecutedMetric_BlockFinalized_Call {
	_c.Call.Return()
	return _c
}

func (_c *CollectionExecutedMetric_BlockFinalized_Call) RunAndReturn(run func(block *flow.Block)) *CollectionExecutedMetric_BlockFinalized_Call {
	_c.Run(run)
	return _c
}

// CollectionExecuted provides a mock function for the type CollectionExecutedMetric
func (_mock *CollectionExecutedMetric) CollectionExecuted(light *flow.LightCollection) {
	_mock.Called(light)
	return
}

// CollectionExecutedMetric_CollectionExecuted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectionExecuted'
type CollectionExecutedMetric_CollectionExecuted_Call struct {
	*mock.Call
}

// CollectionExecuted is a helper method to define mock.On call
//   - light *flow.LightCollection
func (_e *CollectionExecutedMetric_Expecter) CollectionExecuted(light interface{}) *CollectionExecutedMetric_CollectionExecuted_Call {
	return &CollectionExecutedMetric_CollectionExecuted_Call{Call: _e.mock.On("CollectionExecuted", light)}
}

func (_c *CollectionExecutedMetric_CollectionExecuted_Call) Run(run func(light *flow.LightCollection)) *CollectionExecutedMetric_CollectionExecuted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *flow.LightCollection
		if args[0] != nil {
			arg0 = args[0].(*flow.LightCollection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CollectionExecutedMetric_CollectionExecuted_Call) Return() *CollectionExecutedMetric_CollectionExecuted_Call {
	_c.Call.Return()
	return _c
}

func (_c *CollectionExecutedMetric_CollectionExecuted_Call) RunAndReturn(run func(light *flow.LightCollection)) *CollectionExecutedMetric_CollectionExecuted_Call {
	_c.Run(run)
	return _c
}

// CollectionFinalized provides a mock function for the type CollectionExecutedMetric
func (_mock *CollectionExecutedMetric) CollectionFinalized(light *flow.LightCollection) {
	_mock.Called(light)
	return
}

// CollectionExecutedMetric_CollectionFinalized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectionFinalized'
type CollectionExecutedMetric_CollectionFinalized_Call struct {
	*mock.Call
}

// CollectionFinalized is a helper method to define mock.On call
//   - light *flow.LightCollection
func (_e *CollectionExecutedMetric_Expecter) CollectionFinalized(light interface{}) *CollectionExecutedMetric_CollectionFinalized_Call {
	return &CollectionExecutedMetric_CollectionFinalized_Call{Call: _e.mock.On("CollectionFinalized", light)}
}

func (_c *CollectionExecutedMetric_CollectionFinalized_Call) Run(run func(light *flow.LightCollection)) *CollectionExecutedMetric_CollectionFinalized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *flow.LightCollection
		if args[0] != nil {
			arg0 = args[0].(*flow.LightCollection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CollectionExecutedMetric_CollectionFinalized_Call) Return() *CollectionExecutedMetric_CollectionFinalized_Call {
	_c.Call.Return()
	return _c
}

func (_c *CollectionExecutedMetric_CollectionFinalized_Call) RunAndReturn(run func(light *flow.LightCollection)) *CollectionExecutedMetric_CollectionFinalized_Call {
	_c.Run(run)
	return _c
}

// ExecutionReceiptReceived provides a mock function for the type CollectionExecutedMetric
func (_mock *CollectionExecutedMetric) ExecutionReceiptReceived(r *flow.ExecutionReceipt) {
	_mock.Called(r)
	return
}

// CollectionExecutedMetric_ExecutionReceiptReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutionReceiptReceived'
type CollectionExecutedMetric_ExecutionReceiptReceived_Call struct {
	*mock.Call
}

// ExecutionReceiptReceived is a helper method to define mock.On call
//   - r *flow.ExecutionReceipt
func (_e *CollectionExecutedMetric_Expecter) ExecutionReceiptReceived(r interface{}) *CollectionExecutedMetric_ExecutionReceiptReceived_Call {
	return &CollectionExecutedMetric_ExecutionReceiptReceived_Call{Call: _e.mock.On("ExecutionReceiptReceived", r)}
}

func (_c *CollectionExecutedMetric_ExecutionReceiptReceived_Call) Run(run func(r *flow.ExecutionReceipt)) *CollectionExecutedMetric_ExecutionReceiptReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *flow.ExecutionReceipt
		if args[0] != nil {
			arg0 = args[0].(*flow.ExecutionReceipt)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CollectionExecutedMetric_ExecutionReceiptReceived_Call) Return() *CollectionExecutedMetric_ExecutionReceiptReceived_Call {
	_c.Call.Return()
	return _c
}

func (_c *CollectionExecutedMetric_ExecutionReceiptReceived_Call) RunAndReturn(run func(r *flow.ExecutionReceipt)) *CollectionExecutedMetric_ExecutionReceiptReceived_Call {
	_c.Run(run)
	return _c
}

// UpdateLastFullBlockHeight provides a mock function for the type CollectionExecutedMetric
func (_mock *CollectionExecutedMetric) UpdateLastFullBlockHeight(height uint64) {
	_mock.Called(height)
	return
}

// CollectionExecutedMetric_UpdateLastFullBlockHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastFullBlockHeight'
type CollectionExecutedMetric_UpdateLastFullBlockHeight_Call struct {
	*mock.Call
}

// UpdateLastFullBlockHeight is a helper method to define mock.On call
//   - height uint64
func (_e *CollectionExecutedMetric_Expecter) UpdateLastFullBlockHeight(height interface{}) *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call {
	return &CollectionExecutedMetric_UpdateLastFullBlockHeight_Call{Call: _e.mock.On("UpdateLastFullBlockHeight", height)}
}

func (_c *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call) Run(run func(height uint64)) *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call) Return() *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call {
	_c.Call.Return()
	return _c
}

func (_c *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call) RunAndReturn(run func(height uint64)) *CollectionExecutedMetric_UpdateLastFullBlockHeight_Call {
	_c.Run(run)
	return _c
}
