// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	flow "github.com/dapperlabs/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// ConsensusMetrics is an autogenerated mock type for the ConsensusMetrics type
type ConsensusMetrics struct {
	mock.Mock
}

// FinishBlockToSeal provides a mock function with given fields: blockID
func (_m *ConsensusMetrics) FinishBlockToSeal(blockID flow.Identifier) {
	_m.Called(blockID)
}

// FinishCollectionToFinalized provides a mock function with given fields: collectionID
func (_m *ConsensusMetrics) FinishCollectionToFinalized(collectionID flow.Identifier) {
	_m.Called(collectionID)
}

// StartBlockToSeal provides a mock function with given fields: blockID
func (_m *ConsensusMetrics) StartBlockToSeal(blockID flow.Identifier) {
	_m.Called(blockID)
}

// StartCollectionToFinalized provides a mock function with given fields: collectionID
func (_m *ConsensusMetrics) StartCollectionToFinalized(collectionID flow.Identifier) {
	_m.Called(collectionID)
}
