// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewExecutionDataPrunerMetrics creates a new instance of ExecutionDataPrunerMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionDataPrunerMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionDataPrunerMetrics {
	mock := &ExecutionDataPrunerMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ExecutionDataPrunerMetrics is an autogenerated mock type for the ExecutionDataPrunerMetrics type
type ExecutionDataPrunerMetrics struct {
	mock.Mock
}

type ExecutionDataPrunerMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *ExecutionDataPrunerMetrics) EXPECT() *ExecutionDataPrunerMetrics_Expecter {
	return &ExecutionDataPrunerMetrics_Expecter{mock: &_m.Mock}
}

// Pruned provides a mock function for the type ExecutionDataPrunerMetrics
func (_mock *ExecutionDataPrunerMetrics) Pruned(height uint64, duration time.Duration) {
	_mock.Called(height, duration)
	return
}

// ExecutionDataPrunerMetrics_Pruned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pruned'
type ExecutionDataPrunerMetrics_Pruned_Call struct {
	*mock.Call
}

// Pruned is a helper method to define mock.On call
//   - height uint64
//   - duration time.Duration
func (_e *ExecutionDataPrunerMetrics_Expecter) Pruned(height interface{}, duration interface{}) *ExecutionDataPrunerMetrics_Pruned_Call {
	return &ExecutionDataPrunerMetrics_Pruned_Call{Call: _e.mock.On("Pruned", height, duration)}
}

func (_c *ExecutionDataPrunerMetrics_Pruned_Call) Run(run func(height uint64, duration time.Duration)) *ExecutionDataPrunerMetrics_Pruned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ExecutionDataPrunerMetrics_Pruned_Call) Return() *ExecutionDataPrunerMetrics_Pruned_Call {
	_c.Call.Return()
	return _c
}

func (_c *ExecutionDataPrunerMetrics_Pruned_Call) RunAndReturn(run func(height uint64, duration time.Duration)) *ExecutionDataPrunerMetrics_Pruned_Call {
	_c.Run(run)
	return _c
}
