// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockExecutionDataRequesterMetrics is an autogenerated mock type for the ExecutionDataRequesterMetrics type
type MockExecutionDataRequesterMetrics struct {
	mock.Mock
}

type MockExecutionDataRequesterMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutionDataRequesterMetrics) EXPECT() *MockExecutionDataRequesterMetrics_Expecter {
	return &MockExecutionDataRequesterMetrics_Expecter{mock: &_m.Mock}
}

// ExecutionDataFetchFinished provides a mock function with given fields: duration, success, height
func (_m *MockExecutionDataRequesterMetrics) ExecutionDataFetchFinished(duration time.Duration, success bool, height uint64) {
	_m.Called(duration, success, height)
}

// MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutionDataFetchFinished'
type MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call struct {
	*mock.Call
}

// ExecutionDataFetchFinished is a helper method to define mock.On call
//   - duration time.Duration
//   - success bool
//   - height uint64
func (_e *MockExecutionDataRequesterMetrics_Expecter) ExecutionDataFetchFinished(duration interface{}, success interface{}, height interface{}) *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call {
	return &MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call{Call: _e.mock.On("ExecutionDataFetchFinished", duration, success, height)}
}

func (_c *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call) Run(run func(duration time.Duration, success bool, height uint64)) *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(bool), args[2].(uint64))
	})
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call) Return() *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call) RunAndReturn(run func(time.Duration, bool, uint64)) *MockExecutionDataRequesterMetrics_ExecutionDataFetchFinished_Call {
	_c.Run(run)
	return _c
}

// ExecutionDataFetchStarted provides a mock function with no fields
func (_m *MockExecutionDataRequesterMetrics) ExecutionDataFetchStarted() {
	_m.Called()
}

// MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecutionDataFetchStarted'
type MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call struct {
	*mock.Call
}

// ExecutionDataFetchStarted is a helper method to define mock.On call
func (_e *MockExecutionDataRequesterMetrics_Expecter) ExecutionDataFetchStarted() *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call {
	return &MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call{Call: _e.mock.On("ExecutionDataFetchStarted")}
}

func (_c *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call) Run(run func()) *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call) Return() *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call) RunAndReturn(run func()) *MockExecutionDataRequesterMetrics_ExecutionDataFetchStarted_Call {
	_c.Run(run)
	return _c
}

// FetchRetried provides a mock function with no fields
func (_m *MockExecutionDataRequesterMetrics) FetchRetried() {
	_m.Called()
}

// MockExecutionDataRequesterMetrics_FetchRetried_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRetried'
type MockExecutionDataRequesterMetrics_FetchRetried_Call struct {
	*mock.Call
}

// FetchRetried is a helper method to define mock.On call
func (_e *MockExecutionDataRequesterMetrics_Expecter) FetchRetried() *MockExecutionDataRequesterMetrics_FetchRetried_Call {
	return &MockExecutionDataRequesterMetrics_FetchRetried_Call{Call: _e.mock.On("FetchRetried")}
}

func (_c *MockExecutionDataRequesterMetrics_FetchRetried_Call) Run(run func()) *MockExecutionDataRequesterMetrics_FetchRetried_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_FetchRetried_Call) Return() *MockExecutionDataRequesterMetrics_FetchRetried_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_FetchRetried_Call) RunAndReturn(run func()) *MockExecutionDataRequesterMetrics_FetchRetried_Call {
	_c.Run(run)
	return _c
}

// NotificationSent provides a mock function with given fields: height
func (_m *MockExecutionDataRequesterMetrics) NotificationSent(height uint64) {
	_m.Called(height)
}

// MockExecutionDataRequesterMetrics_NotificationSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotificationSent'
type MockExecutionDataRequesterMetrics_NotificationSent_Call struct {
	*mock.Call
}

// NotificationSent is a helper method to define mock.On call
//   - height uint64
func (_e *MockExecutionDataRequesterMetrics_Expecter) NotificationSent(height interface{}) *MockExecutionDataRequesterMetrics_NotificationSent_Call {
	return &MockExecutionDataRequesterMetrics_NotificationSent_Call{Call: _e.mock.On("NotificationSent", height)}
}

func (_c *MockExecutionDataRequesterMetrics_NotificationSent_Call) Run(run func(height uint64)) *MockExecutionDataRequesterMetrics_NotificationSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_NotificationSent_Call) Return() *MockExecutionDataRequesterMetrics_NotificationSent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockExecutionDataRequesterMetrics_NotificationSent_Call) RunAndReturn(run func(uint64)) *MockExecutionDataRequesterMetrics_NotificationSent_Call {
	_c.Run(run)
	return _c
}

// NewMockExecutionDataRequesterMetrics creates a new instance of MockExecutionDataRequesterMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutionDataRequesterMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutionDataRequesterMetrics {
	mock := &MockExecutionDataRequesterMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
