// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ExecutionDataProviderMetrics is an autogenerated mock type for the ExecutionDataProviderMetrics type
type ExecutionDataProviderMetrics struct {
	mock.Mock
}

// AddBlobsFailed provides a mock function with given fields:
func (_m *ExecutionDataProviderMetrics) AddBlobsFailed() {
	_m.Called()
}

// AddBlobsSucceeded provides a mock function with given fields: duration, totalSize
func (_m *ExecutionDataProviderMetrics) AddBlobsSucceeded(duration time.Duration, totalSize uint64) {
	_m.Called(duration, totalSize)
}

// RootIDComputed provides a mock function with given fields: duration, numberOfChunks
func (_m *ExecutionDataProviderMetrics) RootIDComputed(duration time.Duration, numberOfChunks int) {
	_m.Called(duration, numberOfChunks)
}

// NewExecutionDataProviderMetrics creates a new instance of ExecutionDataProviderMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionDataProviderMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionDataProviderMetrics {
	mock := &ExecutionDataProviderMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
