// Code generated by mockery v2.21.4. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	irrecoverable "github.com/onflow/flow-go/module/irrecoverable"

	model "github.com/onflow/flow-go/consensus/hotstuff/model"
)

// HotStuffFollower is an autogenerated mock type for the HotStuffFollower type
type HotStuffFollower struct {
	mock.Mock
}

// AddCertifiedBlock provides a mock function with given fields: certifiedBlock
func (_m *HotStuffFollower) AddCertifiedBlock(certifiedBlock *model.CertifiedBlock) {
	_m.Called(certifiedBlock)
}

// Done provides a mock function with given fields:
func (_m *HotStuffFollower) Done() <-chan struct{} {
	ret := _m.Called()

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// Ready provides a mock function with given fields:
func (_m *HotStuffFollower) Ready() <-chan struct{} {
	ret := _m.Called()

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// Start provides a mock function with given fields: _a0
func (_m *HotStuffFollower) Start(_a0 irrecoverable.SignalerContext) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewHotStuffFollower interface {
	mock.TestingT
	Cleanup(func())
}

// NewHotStuffFollower creates a new instance of HotStuffFollower. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHotStuffFollower(t mockConstructorTestingTNewHotStuffFollower) *HotStuffFollower {
	mock := &HotStuffFollower{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
