// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	crypto "github.com/dapperlabs/flow-go/crypto"
	collection "github.com/dapperlabs/flow-go/model/collection"

	mock "github.com/stretchr/testify/mock"
)

// mempool is an autogenerated mock type for the mempool type
type Mempool struct {
	mock.Mock
}

// Add provides a mock function with given fields: coll
func (_m *Mempool) Add(coll *collection.GuaranteedCollection) error {
	ret := _m.Called(coll)

	var r0 error
	if rf, ok := ret.Get(0).(func(*collection.GuaranteedCollection) error); ok {
		r0 = rf(coll)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// All provides a mock function with given fields:
func (_m *Mempool) All() []*collection.GuaranteedCollection {
	ret := _m.Called()

	var r0 []*collection.GuaranteedCollection
	if rf, ok := ret.Get(0).(func() []*collection.GuaranteedCollection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*collection.GuaranteedCollection)
		}
	}

	return r0
}

// Get provides a mock function with given fields: hash
func (_m *Mempool) Get(hash crypto.Hash) (*collection.GuaranteedCollection, error) {
	ret := _m.Called(hash)

	var r0 *collection.GuaranteedCollection
	if rf, ok := ret.Get(0).(func(crypto.Hash) *collection.GuaranteedCollection); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collection.GuaranteedCollection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(crypto.Hash) error); ok {
		r1 = rf(hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Has provides a mock function with given fields: hash
func (_m *Mempool) Has(hash crypto.Hash) bool {
	ret := _m.Called(hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(crypto.Hash) bool); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Hash provides a mock function with given fields:
func (_m *Mempool) Hash() crypto.Hash {
	ret := _m.Called()

	var r0 crypto.Hash
	if rf, ok := ret.Get(0).(func() crypto.Hash); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.Hash)
		}
	}

	return r0
}

// Rem provides a mock function with given fields: hash
func (_m *Mempool) Rem(hash crypto.Hash) bool {
	ret := _m.Called(hash)

	var r0 bool
	if rf, ok := ret.Get(0).(func(crypto.Hash) bool); ok {
		r0 = rf(hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Size provides a mock function with given fields:
func (_m *Mempool) Size() uint {
	ret := _m.Called()

	var r0 uint
	if rf, ok := ret.Get(0).(func() uint); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint)
	}

	return r0
}
