// Code generated by mockery v2.12.1. DO NOT EDIT.

package mock

import (
	flow "github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"

	testing "testing"

	time "time"
)

// PingMetrics is an autogenerated mock type for the PingMetrics type
type PingMetrics struct {
	mock.Mock
}

// NodeInfo provides a mock function with given fields: node, nodeInfo, version, sealedHeight, hotstuffCurView
func (_m *PingMetrics) NodeInfo(node *flow.Identity, nodeInfo string, version string, sealedHeight uint64, hotstuffCurView uint64) {
	_m.Called(node, nodeInfo, version, sealedHeight, hotstuffCurView)
}

// NodeReachable provides a mock function with given fields: node, nodeInfo, rtt
func (_m *PingMetrics) NodeReachable(node *flow.Identity, nodeInfo string, rtt time.Duration) {
	_m.Called(node, nodeInfo, rtt)
}

// NewPingMetrics creates a new instance of PingMetrics. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPingMetrics(t testing.TB) *PingMetrics {
	mock := &PingMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
