// Code generated by mockery v2.12.1. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ProviderMetrics is an autogenerated mock type for the ProviderMetrics type
type ProviderMetrics struct {
	mock.Mock
}

// ChunkDataPackRequested provides a mock function with given fields:
func (_m *ProviderMetrics) ChunkDataPackRequested() {
	_m.Called()
}

// NewProviderMetrics creates a new instance of ProviderMetrics. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewProviderMetrics(t testing.TB) *ProviderMetrics {
	mock := &ProviderMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
