// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	crypto "github.com/onflow/crypto"
	mock "github.com/stretchr/testify/mock"
)

// RandomBeaconKeyStore is an autogenerated mock type for the RandomBeaconKeyStore type
type RandomBeaconKeyStore struct {
	mock.Mock
}

// ByView provides a mock function with given fields: view
func (_m *RandomBeaconKeyStore) ByView(view uint64) (crypto.PrivateKey, error) {
	ret := _m.Called(view)

	if len(ret) == 0 {
		panic("no return value specified for ByView")
	}

	var r0 crypto.PrivateKey
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (crypto.PrivateKey, error)); ok {
		return rf(view)
	}
	if rf, ok := ret.Get(0).(func(uint64) crypto.PrivateKey); ok {
		r0 = rf(view)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivateKey)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(view)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRandomBeaconKeyStore creates a new instance of RandomBeaconKeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRandomBeaconKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RandomBeaconKeyStore {
	mock := &RandomBeaconKeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
