// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	crypto "github.com/onflow/flow-go/crypto"
	mock "github.com/stretchr/testify/mock"
)

// RandomBeaconKeyStore is an autogenerated mock type for the RandomBeaconKeyStore type
type RandomBeaconKeyStore struct {
	mock.Mock
}

// ByView provides a mock function with given fields: view
func (_m *RandomBeaconKeyStore) ByView(view uint64) (crypto.PrivateKey, error) {
	ret := _m.Called(view)

	var r0 crypto.PrivateKey
	if rf, ok := ret.Get(0).(func(uint64) crypto.PrivateKey); ok {
		r0 = rf(view)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivateKey)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(view)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
