// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	flow "github.com/dapperlabs/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"

	module "github.com/dapperlabs/flow-go/module"
)

// Requester is an autogenerated mock type for the Requester type
type Requester struct {
	mock.Mock
}

// Request provides a mock function with given fields: entityID, handle
func (_m *Requester) Request(entityID flow.Identifier, handle module.HandleFunc) error {
	ret := _m.Called(entityID, handle)

	var r0 error
	if rf, ok := ret.Get(0).(func(flow.Identifier, module.HandleFunc) error); ok {
		r0 = rf(entityID, handle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
