// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
)

// NewVerificationMetrics creates a new instance of VerificationMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationMetrics {
	mock := &VerificationMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VerificationMetrics is an autogenerated mock type for the VerificationMetrics type
type VerificationMetrics struct {
	mock.Mock
}

type VerificationMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *VerificationMetrics) EXPECT() *VerificationMetrics_Expecter {
	return &VerificationMetrics_Expecter{mock: &_m.Mock}
}

// OnAssignedChunkProcessedAtAssigner provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnAssignedChunkProcessedAtAssigner() {
	_mock.Called()
	return
}

// VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnAssignedChunkProcessedAtAssigner'
type VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call struct {
	*mock.Call
}

// OnAssignedChunkProcessedAtAssigner is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnAssignedChunkProcessedAtAssigner() *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call {
	return &VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call{Call: _e.mock.On("OnAssignedChunkProcessedAtAssigner")}
}

func (_c *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call) Run(run func()) *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call) Return() *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call) RunAndReturn(run func()) *VerificationMetrics_OnAssignedChunkProcessedAtAssigner_Call {
	_c.Run(run)
	return _c
}

// OnAssignedChunkReceivedAtFetcher provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnAssignedChunkReceivedAtFetcher() {
	_mock.Called()
	return
}

// VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnAssignedChunkReceivedAtFetcher'
type VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call struct {
	*mock.Call
}

// OnAssignedChunkReceivedAtFetcher is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnAssignedChunkReceivedAtFetcher() *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call {
	return &VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call{Call: _e.mock.On("OnAssignedChunkReceivedAtFetcher")}
}

func (_c *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call) Run(run func()) *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call) Return() *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call) RunAndReturn(run func()) *VerificationMetrics_OnAssignedChunkReceivedAtFetcher_Call {
	_c.Run(run)
	return _c
}

// OnBlockConsumerJobDone provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnBlockConsumerJobDone(v uint64) {
	_mock.Called(v)
	return
}

// VerificationMetrics_OnBlockConsumerJobDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnBlockConsumerJobDone'
type VerificationMetrics_OnBlockConsumerJobDone_Call struct {
	*mock.Call
}

// OnBlockConsumerJobDone is a helper method to define mock.On call
//   - v uint64
func (_e *VerificationMetrics_Expecter) OnBlockConsumerJobDone(v interface{}) *VerificationMetrics_OnBlockConsumerJobDone_Call {
	return &VerificationMetrics_OnBlockConsumerJobDone_Call{Call: _e.mock.On("OnBlockConsumerJobDone", v)}
}

func (_c *VerificationMetrics_OnBlockConsumerJobDone_Call) Run(run func(v uint64)) *VerificationMetrics_OnBlockConsumerJobDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VerificationMetrics_OnBlockConsumerJobDone_Call) Return() *VerificationMetrics_OnBlockConsumerJobDone_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnBlockConsumerJobDone_Call) RunAndReturn(run func(v uint64)) *VerificationMetrics_OnBlockConsumerJobDone_Call {
	_c.Run(run)
	return _c
}

// OnChunkConsumerJobDone provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkConsumerJobDone(v uint64) {
	_mock.Called(v)
	return
}

// VerificationMetrics_OnChunkConsumerJobDone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkConsumerJobDone'
type VerificationMetrics_OnChunkConsumerJobDone_Call struct {
	*mock.Call
}

// OnChunkConsumerJobDone is a helper method to define mock.On call
//   - v uint64
func (_e *VerificationMetrics_Expecter) OnChunkConsumerJobDone(v interface{}) *VerificationMetrics_OnChunkConsumerJobDone_Call {
	return &VerificationMetrics_OnChunkConsumerJobDone_Call{Call: _e.mock.On("OnChunkConsumerJobDone", v)}
}

func (_c *VerificationMetrics_OnChunkConsumerJobDone_Call) Run(run func(v uint64)) *VerificationMetrics_OnChunkConsumerJobDone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkConsumerJobDone_Call) Return() *VerificationMetrics_OnChunkConsumerJobDone_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkConsumerJobDone_Call) RunAndReturn(run func(v uint64)) *VerificationMetrics_OnChunkConsumerJobDone_Call {
	_c.Run(run)
	return _c
}

// OnChunkDataPackArrivedAtFetcher provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkDataPackArrivedAtFetcher() {
	_mock.Called()
	return
}

// VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkDataPackArrivedAtFetcher'
type VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call struct {
	*mock.Call
}

// OnChunkDataPackArrivedAtFetcher is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnChunkDataPackArrivedAtFetcher() *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call {
	return &VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call{Call: _e.mock.On("OnChunkDataPackArrivedAtFetcher")}
}

func (_c *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call) Run(run func()) *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call) Return() *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call) RunAndReturn(run func()) *VerificationMetrics_OnChunkDataPackArrivedAtFetcher_Call {
	_c.Run(run)
	return _c
}

// OnChunkDataPackRequestDispatchedInNetworkByRequester provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkDataPackRequestDispatchedInNetworkByRequester() {
	_mock.Called()
	return
}

// VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkDataPackRequestDispatchedInNetworkByRequester'
type VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call struct {
	*mock.Call
}

// OnChunkDataPackRequestDispatchedInNetworkByRequester is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnChunkDataPackRequestDispatchedInNetworkByRequester() *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call {
	return &VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call{Call: _e.mock.On("OnChunkDataPackRequestDispatchedInNetworkByRequester")}
}

func (_c *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call) Run(run func()) *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call) Return() *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call) RunAndReturn(run func()) *VerificationMetrics_OnChunkDataPackRequestDispatchedInNetworkByRequester_Call {
	_c.Run(run)
	return _c
}

// OnChunkDataPackRequestReceivedByRequester provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkDataPackRequestReceivedByRequester() {
	_mock.Called()
	return
}

// VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkDataPackRequestReceivedByRequester'
type VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call struct {
	*mock.Call
}

// OnChunkDataPackRequestReceivedByRequester is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnChunkDataPackRequestReceivedByRequester() *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call {
	return &VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call{Call: _e.mock.On("OnChunkDataPackRequestReceivedByRequester")}
}

func (_c *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call) Run(run func()) *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call) Return() *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call) RunAndReturn(run func()) *VerificationMetrics_OnChunkDataPackRequestReceivedByRequester_Call {
	_c.Run(run)
	return _c
}

// OnChunkDataPackRequestSentByFetcher provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkDataPackRequestSentByFetcher() {
	_mock.Called()
	return
}

// VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkDataPackRequestSentByFetcher'
type VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call struct {
	*mock.Call
}

// OnChunkDataPackRequestSentByFetcher is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnChunkDataPackRequestSentByFetcher() *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call {
	return &VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call{Call: _e.mock.On("OnChunkDataPackRequestSentByFetcher")}
}

func (_c *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call) Run(run func()) *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call) Return() *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call) RunAndReturn(run func()) *VerificationMetrics_OnChunkDataPackRequestSentByFetcher_Call {
	_c.Run(run)
	return _c
}

// OnChunkDataPackResponseReceivedFromNetworkByRequester provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkDataPackResponseReceivedFromNetworkByRequester() {
	_mock.Called()
	return
}

// VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkDataPackResponseReceivedFromNetworkByRequester'
type VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call struct {
	*mock.Call
}

// OnChunkDataPackResponseReceivedFromNetworkByRequester is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnChunkDataPackResponseReceivedFromNetworkByRequester() *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call {
	return &VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call{Call: _e.mock.On("OnChunkDataPackResponseReceivedFromNetworkByRequester")}
}

func (_c *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call) Run(run func()) *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call) Return() *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call) RunAndReturn(run func()) *VerificationMetrics_OnChunkDataPackResponseReceivedFromNetworkByRequester_Call {
	_c.Run(run)
	return _c
}

// OnChunkDataPackSentToFetcher provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunkDataPackSentToFetcher() {
	_mock.Called()
	return
}

// VerificationMetrics_OnChunkDataPackSentToFetcher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunkDataPackSentToFetcher'
type VerificationMetrics_OnChunkDataPackSentToFetcher_Call struct {
	*mock.Call
}

// OnChunkDataPackSentToFetcher is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnChunkDataPackSentToFetcher() *VerificationMetrics_OnChunkDataPackSentToFetcher_Call {
	return &VerificationMetrics_OnChunkDataPackSentToFetcher_Call{Call: _e.mock.On("OnChunkDataPackSentToFetcher")}
}

func (_c *VerificationMetrics_OnChunkDataPackSentToFetcher_Call) Run(run func()) *VerificationMetrics_OnChunkDataPackSentToFetcher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackSentToFetcher_Call) Return() *VerificationMetrics_OnChunkDataPackSentToFetcher_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunkDataPackSentToFetcher_Call) RunAndReturn(run func()) *VerificationMetrics_OnChunkDataPackSentToFetcher_Call {
	_c.Run(run)
	return _c
}

// OnChunksAssignmentDoneAtAssigner provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnChunksAssignmentDoneAtAssigner(chunks int) {
	_mock.Called(chunks)
	return
}

// VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnChunksAssignmentDoneAtAssigner'
type VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call struct {
	*mock.Call
}

// OnChunksAssignmentDoneAtAssigner is a helper method to define mock.On call
//   - chunks int
func (_e *VerificationMetrics_Expecter) OnChunksAssignmentDoneAtAssigner(chunks interface{}) *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call {
	return &VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call{Call: _e.mock.On("OnChunksAssignmentDoneAtAssigner", chunks)}
}

func (_c *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call) Run(run func(chunks int)) *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call) Return() *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call) RunAndReturn(run func(chunks int)) *VerificationMetrics_OnChunksAssignmentDoneAtAssigner_Call {
	_c.Run(run)
	return _c
}

// OnExecutionResultReceivedAtAssignerEngine provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnExecutionResultReceivedAtAssignerEngine() {
	_mock.Called()
	return
}

// VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnExecutionResultReceivedAtAssignerEngine'
type VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call struct {
	*mock.Call
}

// OnExecutionResultReceivedAtAssignerEngine is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnExecutionResultReceivedAtAssignerEngine() *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call {
	return &VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call{Call: _e.mock.On("OnExecutionResultReceivedAtAssignerEngine")}
}

func (_c *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call) Run(run func()) *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call) Return() *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call) RunAndReturn(run func()) *VerificationMetrics_OnExecutionResultReceivedAtAssignerEngine_Call {
	_c.Run(run)
	return _c
}

// OnFinalizedBlockArrivedAtAssigner provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnFinalizedBlockArrivedAtAssigner(height uint64) {
	_mock.Called(height)
	return
}

// VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnFinalizedBlockArrivedAtAssigner'
type VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call struct {
	*mock.Call
}

// OnFinalizedBlockArrivedAtAssigner is a helper method to define mock.On call
//   - height uint64
func (_e *VerificationMetrics_Expecter) OnFinalizedBlockArrivedAtAssigner(height interface{}) *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call {
	return &VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call{Call: _e.mock.On("OnFinalizedBlockArrivedAtAssigner", height)}
}

func (_c *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call) Run(run func(height uint64)) *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call) Return() *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call) RunAndReturn(run func(height uint64)) *VerificationMetrics_OnFinalizedBlockArrivedAtAssigner_Call {
	_c.Run(run)
	return _c
}

// OnResultApprovalDispatchedInNetworkByVerifier provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnResultApprovalDispatchedInNetworkByVerifier() {
	_mock.Called()
	return
}

// VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnResultApprovalDispatchedInNetworkByVerifier'
type VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call struct {
	*mock.Call
}

// OnResultApprovalDispatchedInNetworkByVerifier is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnResultApprovalDispatchedInNetworkByVerifier() *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call {
	return &VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call{Call: _e.mock.On("OnResultApprovalDispatchedInNetworkByVerifier")}
}

func (_c *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call) Run(run func()) *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call) Return() *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call) RunAndReturn(run func()) *VerificationMetrics_OnResultApprovalDispatchedInNetworkByVerifier_Call {
	_c.Run(run)
	return _c
}

// OnVerifiableChunkReceivedAtVerifierEngine provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnVerifiableChunkReceivedAtVerifierEngine() {
	_mock.Called()
	return
}

// VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnVerifiableChunkReceivedAtVerifierEngine'
type VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call struct {
	*mock.Call
}

// OnVerifiableChunkReceivedAtVerifierEngine is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnVerifiableChunkReceivedAtVerifierEngine() *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call {
	return &VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call{Call: _e.mock.On("OnVerifiableChunkReceivedAtVerifierEngine")}
}

func (_c *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call) Run(run func()) *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call) Return() *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call) RunAndReturn(run func()) *VerificationMetrics_OnVerifiableChunkReceivedAtVerifierEngine_Call {
	_c.Run(run)
	return _c
}

// OnVerifiableChunkSentToVerifier provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) OnVerifiableChunkSentToVerifier() {
	_mock.Called()
	return
}

// VerificationMetrics_OnVerifiableChunkSentToVerifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnVerifiableChunkSentToVerifier'
type VerificationMetrics_OnVerifiableChunkSentToVerifier_Call struct {
	*mock.Call
}

// OnVerifiableChunkSentToVerifier is a helper method to define mock.On call
func (_e *VerificationMetrics_Expecter) OnVerifiableChunkSentToVerifier() *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call {
	return &VerificationMetrics_OnVerifiableChunkSentToVerifier_Call{Call: _e.mock.On("OnVerifiableChunkSentToVerifier")}
}

func (_c *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call) Run(run func()) *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call) Return() *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call) RunAndReturn(run func()) *VerificationMetrics_OnVerifiableChunkSentToVerifier_Call {
	_c.Run(run)
	return _c
}

// SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester provides a mock function for the type VerificationMetrics
func (_mock *VerificationMetrics) SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester(attempts uint64) {
	_mock.Called(attempts)
	return
}

// VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester'
type VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call struct {
	*mock.Call
}

// SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester is a helper method to define mock.On call
//   - attempts uint64
func (_e *VerificationMetrics_Expecter) SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester(attempts interface{}) *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call {
	return &VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call{Call: _e.mock.On("SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester", attempts)}
}

func (_c *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call) Run(run func(attempts uint64)) *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call) Return() *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call {
	_c.Call.Return()
	return _c
}

func (_c *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call) RunAndReturn(run func(attempts uint64)) *VerificationMetrics_SetMaxChunkDataPackAttemptsForNextUnsealedHeightAtRequester_Call {
	_c.Run(run)
	return _c
}
