message(STATUS "Available architectures (default = X64):")

message("   ARCH=AVR       Atmel AVR ATMega128 8-bit architecture.")
message("   ARCH=MSP       TI MSP430 16-bit architecture.")
message("   ARCH=ARM       ARM 32-bit architecture.")
message("   ARCH=X86       Intel x86-compatible 32-bit architecture.")
message("   ARCH=X64       AMD x86_64-compatible 64-bit architecture.")
message("   ARCH=NONE      No specific architecture (disable some features).\n")

message(STATUS "Available word sizes (default = 64):")
message("   WORD=8         Build a 8-bit library.")
message("   WORD=16        Build a 16-bit library.")
message("   WORD=32        Build a 32-bit library.")
message("   WORD=64        Build a 64-bit library.\n")

message(STATUS "Byte boundary to align digit vectors (default = 1):")
message("   ALIGN=1        Do not align digit vectors.")
message("   ALIGN=2        Align digit vectors into 16-bit boundaries.")
message("   ALIGN=8        Align digit vectors into 64-bit boundaries.")
message("   ALIGN=16       Align digit vectors into 128-bit boundaries.\n")

# Architecture and memory layout.
if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
	set(ARCH "X64" CACHE STRING "Architecture")
	set(WORD 64 CACHE INTEGER "Processor word size")
else(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
	if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
		set(ARCH "X86" CACHE STRING "Architecture")
		set(WORD 32 CACHE INTEGER "Processor word size")
	endif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
endif(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
set(ARCH "X86_64" CACHE STRING "Architecture")
set(WORD 64 CACHE INTEGER "Processor word size")
set(ALIGN 1 CACHE INTEGER "Boundary to align digit vectors")
