/*
 * flow/access/access.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type EntitiesAccount struct {

	Address string `json:"address,omitempty"`

	Balance string `json:"balance,omitempty"`

	Code string `json:"code,omitempty"`

	Keys []EntitiesAccountKey `json:"keys,omitempty"`

	Contracts map[string]string `json:"contracts,omitempty"`
}
