// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import (
	flow "github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// MockFinalizedReader is an autogenerated mock type for the FinalizedReader type
type MockFinalizedReader struct {
	mock.Mock
}

type MockFinalizedReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinalizedReader) EXPECT() *MockFinalizedReader_Expecter {
	return &MockFinalizedReader_Expecter{mock: &_m.Mock}
}

// FinalizedBlockIDAtHeight provides a mock function with given fields: height
func (_m *MockFinalizedReader) FinalizedBlockIDAtHeight(height uint64) (flow.Identifier, error) {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for FinalizedBlockIDAtHeight")
	}

	var r0 flow.Identifier
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (flow.Identifier, error)); ok {
		return rf(height)
	}
	if rf, ok := ret.Get(0).(func(uint64) flow.Identifier); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(flow.Identifier)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFinalizedReader_FinalizedBlockIDAtHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinalizedBlockIDAtHeight'
type MockFinalizedReader_FinalizedBlockIDAtHeight_Call struct {
	*mock.Call
}

// FinalizedBlockIDAtHeight is a helper method to define mock.On call
//   - height uint64
func (_e *MockFinalizedReader_Expecter) FinalizedBlockIDAtHeight(height interface{}) *MockFinalizedReader_FinalizedBlockIDAtHeight_Call {
	return &MockFinalizedReader_FinalizedBlockIDAtHeight_Call{Call: _e.mock.On("FinalizedBlockIDAtHeight", height)}
}

func (_c *MockFinalizedReader_FinalizedBlockIDAtHeight_Call) Run(run func(height uint64)) *MockFinalizedReader_FinalizedBlockIDAtHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockFinalizedReader_FinalizedBlockIDAtHeight_Call) Return(_a0 flow.Identifier, _a1 error) *MockFinalizedReader_FinalizedBlockIDAtHeight_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFinalizedReader_FinalizedBlockIDAtHeight_Call) RunAndReturn(run func(uint64) (flow.Identifier, error)) *MockFinalizedReader_FinalizedBlockIDAtHeight_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFinalizedReader creates a new instance of MockFinalizedReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinalizedReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinalizedReader {
	mock := &MockFinalizedReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
