// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/onflow/flow-go/model/flow"
	mock "github.com/stretchr/testify/mock"
)

// NewScriptExecutor creates a new instance of ScriptExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScriptExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScriptExecutor {
	mock := &ScriptExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ScriptExecutor is an autogenerated mock type for the ScriptExecutor type
type ScriptExecutor struct {
	mock.Mock
}

type ScriptExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *ScriptExecutor) EXPECT() *ScriptExecutor_Expecter {
	return &ScriptExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteScriptAtBlockID provides a mock function for the type ScriptExecutor
func (_mock *ScriptExecutor) ExecuteScriptAtBlockID(ctx context.Context, script []byte, arguments [][]byte, blockID flow.Identifier) ([]byte, uint64, error) {
	ret := _mock.Called(ctx, script, arguments, blockID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteScriptAtBlockID")
	}

	var r0 []byte
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, [][]byte, flow.Identifier) ([]byte, uint64, error)); ok {
		return returnFunc(ctx, script, arguments, blockID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, [][]byte, flow.Identifier) []byte); ok {
		r0 = returnFunc(ctx, script, arguments, blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, [][]byte, flow.Identifier) uint64); ok {
		r1 = returnFunc(ctx, script, arguments, blockID)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []byte, [][]byte, flow.Identifier) error); ok {
		r2 = returnFunc(ctx, script, arguments, blockID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ScriptExecutor_ExecuteScriptAtBlockID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteScriptAtBlockID'
type ScriptExecutor_ExecuteScriptAtBlockID_Call struct {
	*mock.Call
}

// ExecuteScriptAtBlockID is a helper method to define mock.On call
//   - ctx context.Context
//   - script []byte
//   - arguments [][]byte
//   - blockID flow.Identifier
func (_e *ScriptExecutor_Expecter) ExecuteScriptAtBlockID(ctx interface{}, script interface{}, arguments interface{}, blockID interface{}) *ScriptExecutor_ExecuteScriptAtBlockID_Call {
	return &ScriptExecutor_ExecuteScriptAtBlockID_Call{Call: _e.mock.On("ExecuteScriptAtBlockID", ctx, script, arguments, blockID)}
}

func (_c *ScriptExecutor_ExecuteScriptAtBlockID_Call) Run(run func(ctx context.Context, script []byte, arguments [][]byte, blockID flow.Identifier)) *ScriptExecutor_ExecuteScriptAtBlockID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 [][]byte
		if args[2] != nil {
			arg2 = args[2].([][]byte)
		}
		var arg3 flow.Identifier
		if args[3] != nil {
			arg3 = args[3].(flow.Identifier)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ScriptExecutor_ExecuteScriptAtBlockID_Call) Return(bytes []byte, v uint64, err error) *ScriptExecutor_ExecuteScriptAtBlockID_Call {
	_c.Call.Return(bytes, v, err)
	return _c
}

func (_c *ScriptExecutor_ExecuteScriptAtBlockID_Call) RunAndReturn(run func(ctx context.Context, script []byte, arguments [][]byte, blockID flow.Identifier) ([]byte, uint64, error)) *ScriptExecutor_ExecuteScriptAtBlockID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type ScriptExecutor
func (_mock *ScriptExecutor) GetAccount(ctx context.Context, address flow.Address, blockID flow.Identifier) (*flow.Account, error) {
	ret := _mock.Called(ctx, address, blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *flow.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, flow.Address, flow.Identifier) (*flow.Account, error)); ok {
		return returnFunc(ctx, address, blockID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, flow.Address, flow.Identifier) *flow.Account); ok {
		r0 = returnFunc(ctx, address, blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flow.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, flow.Address, flow.Identifier) error); ok {
		r1 = returnFunc(ctx, address, blockID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScriptExecutor_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type ScriptExecutor_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - address flow.Address
//   - blockID flow.Identifier
func (_e *ScriptExecutor_Expecter) GetAccount(ctx interface{}, address interface{}, blockID interface{}) *ScriptExecutor_GetAccount_Call {
	return &ScriptExecutor_GetAccount_Call{Call: _e.mock.On("GetAccount", ctx, address, blockID)}
}

func (_c *ScriptExecutor_GetAccount_Call) Run(run func(ctx context.Context, address flow.Address, blockID flow.Identifier)) *ScriptExecutor_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 flow.Address
		if args[1] != nil {
			arg1 = args[1].(flow.Address)
		}
		var arg2 flow.Identifier
		if args[2] != nil {
			arg2 = args[2].(flow.Identifier)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ScriptExecutor_GetAccount_Call) Return(account *flow.Account, err error) *ScriptExecutor_GetAccount_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *ScriptExecutor_GetAccount_Call) RunAndReturn(run func(ctx context.Context, address flow.Address, blockID flow.Identifier) (*flow.Account, error)) *ScriptExecutor_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetRegisterAtBlockID provides a mock function for the type ScriptExecutor
func (_mock *ScriptExecutor) GetRegisterAtBlockID(ctx context.Context, owner []byte, key []byte, blockID flow.Identifier) ([]byte, error) {
	ret := _mock.Called(ctx, owner, key, blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetRegisterAtBlockID")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte, flow.Identifier) ([]byte, error)); ok {
		return returnFunc(ctx, owner, key, blockID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte, []byte, flow.Identifier) []byte); ok {
		r0 = returnFunc(ctx, owner, key, blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte, []byte, flow.Identifier) error); ok {
		r1 = returnFunc(ctx, owner, key, blockID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ScriptExecutor_GetRegisterAtBlockID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRegisterAtBlockID'
type ScriptExecutor_GetRegisterAtBlockID_Call struct {
	*mock.Call
}

// GetRegisterAtBlockID is a helper method to define mock.On call
//   - ctx context.Context
//   - owner []byte
//   - key []byte
//   - blockID flow.Identifier
func (_e *ScriptExecutor_Expecter) GetRegisterAtBlockID(ctx interface{}, owner interface{}, key interface{}, blockID interface{}) *ScriptExecutor_GetRegisterAtBlockID_Call {
	return &ScriptExecutor_GetRegisterAtBlockID_Call{Call: _e.mock.On("GetRegisterAtBlockID", ctx, owner, key, blockID)}
}

func (_c *ScriptExecutor_GetRegisterAtBlockID_Call) Run(run func(ctx context.Context, owner []byte, key []byte, blockID flow.Identifier)) *ScriptExecutor_GetRegisterAtBlockID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 flow.Identifier
		if args[3] != nil {
			arg3 = args[3].(flow.Identifier)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ScriptExecutor_GetRegisterAtBlockID_Call) Return(bytes []byte, err error) *ScriptExecutor_GetRegisterAtBlockID_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *ScriptExecutor_GetRegisterAtBlockID_Call) RunAndReturn(run func(ctx context.Context, owner []byte, key []byte, blockID flow.Identifier) ([]byte, error)) *ScriptExecutor_GetRegisterAtBlockID_Call {
	_c.Call.Return(run)
	return _c
}
